### ISSUE TITLE
Zaproxy complains to ARRAffinity cookie.

### ISSUE THREAD

**Issue by vladbilyk** [zaproxy/zaproxy#1672]
For Azure deployed web sites Zaproxy shows alert "Cookie set without HttpOnly flag" to ARRAffinity cookies which are part of Azure routing infrastructure (http://azure.microsoft.com/blog/2013/11/18/disabling-arrs-instance-affinity-in-windows-azure-web-sites/), but it doesn't look dangerous. Could you please tune the "Cookie set without HttpOnly flag" rule to dismiss the Azure ARRAffinity cookies?

**Comment by kingthorin** [comment]
From a security perspective the server is mis-configured. There is no reason for the cookie at issue to be manipulated via client side script therefore it should indeed be set as HttpOnly. [Unless I'm missing something.]

Remaining options would seem to be:
1) Turn it off if it's not needed (you provided instructions yourself).
2) Configure the server/functionality appropriately. (Which may mean leaning on Microsoft.)

If your app is subject to an XSS flaw etc do you want that injected code to have access to this cookie?

Ref: https://www.owasp.org/index.php/HttpOnly

**Comment by vladbilyk** [comment]
Pro forma I agree, that  the server is mis-configured, but practically these cookies are nothing more than bytes of data intended to tie clients to site instances and contain nothing of a personal nature nor provide any conceivable upside for an attacker (at least not that I can think of). Therefore I believe that from security perspective it is not an issue. I also will try to get comments from Microsoft side.

**Comment by kingthorin** [comment]
Perhaps I'm missing something but based on the the statement:
"This way, we can be sure that once a client establishes a session with a specific server instance, it will keep talking to the same server as long as his session is active. This is of particular importance for session-sensitive application (a.k.a. stateless applications), because the session-specific data won’t move from one server to another on its own."
I take that to mean that if I was trying to carryout some sort of session hijacking or user impersonation attack I'd need this cookie (perhaps along with a ASP.NET_SessionID, therefore as I understand having it flagged HTTPOnly would make it more difficult for a malicious user to harvest this cookie (if client side scripting can't access it, then it can't be grabbed via XSS, etc).

**Comment by kingthorin** [comment]
@vladbilyk can this be closed?

**Comment by vladbilyk** [comment]
@kingthorin: I'm fine
