### ISSUE TITLE
Private IP Disclosure - False Positive

### ISSUE THREAD

**Issue by joekir** [zaproxy/zaproxy#1673]
Looks like the pattern matching for private IPs should be tightened up, this got flagged from a http payload today for me

cdDTO":{"size":25150090,"packageVersion":"10.7.31.9","price"

there is probably a regex improvment to be made.

e.g. this would avoid the package version issue (just there are many possible permutations and you can't have variable length lookbehinds so it could end up quite explicit :()
`(?<!packageVersion":")((?:10|172|192)\.\d{1,3}\.\d{1,3}\.\d{1,3})`

Probably the better option is to do it in 2 passes capturing the line with the ip instead of the capture group and verifying in a second match that it doesn't mention version.

**Comment by kingthorin** [comment]
Unfortunately your "packageVersion" number is indeed a valid internal IP.
https://tools.ietf.org/html/rfc1918
http://whois.arin.net/rest/net/NET-10-0-0-0-1/pft

We can't possibly account for all the possible strings that might appear in proximity to a pattern that matches an IP and exclude them on that basis.

Consider some web content such as:
"please upgrade to package version 10.7.31.9."
https://regex101.com/r/sB2dR0/1

Trying to predict every possible context that a private IP might be found in that isn't a security issue wouldn't tighten things up it would probably increase our false negative rate. IMHO from a security perspective it's better for users to have to flag a few findings as False Positive or to disable a certain check in their scan policy (once they've determined that it isn't benefiting them).

**Comment by joekir** [comment]
I know it __could__ be a valid IP in a different context, that isn't t really the point I was making.

*" that isn't a security issue wouldn't tighten things up it would probably increase our false negative rate. IMHO from a security perspective it's better for users to have to flag a few findings as False Positive or to disable a certain check in their scan policy (once they've determined that it isn't benefiting them)."*        
I disagree, in your statement that its better for users to discern FPs from the results, if your target market is non-security users, then low FP rate is indeed a goal to reduce noise.

Its a shame that you wouldn't even consider solutions to the problem. 
Reversing the input string prior to matching, would allow you to use a negative-lookahead instead, which isn't fixed width e.g. https://regex101.com/r/bP0tB9/1

**Comment by psiinon** [comment]
We actually want the rules to be configurable as possible so that users can tune them to meet their requirements.
We have the concept of Threasholds which allows uses to say whether they want more or less potential false positives/false negatives.
So I would have no problem having tighter regexes on the High threshold, although exactly what they should be I leave open for discussion ;)
Working out ways to filter out strings that are actually valid IP addresses could be very tricky - all suggestions appreciated :)

**Comment by kingthorin** [comment]
@joekir I wasn't meaning to suggest that the issue was dropped or closed. I'm totally up for discussion on the matter, as psiinon suggests we need to come up with a way to strike the right balance. While I agree that reducing false positives is a worthy goal, however we don't want to reduce FPs while increasing FNs. 

Can you expand upon your example (https://regex101.com/r/bP0tB9/1) a bit more? I'm kind of confused because I thought you wanted to avoid the match in your case but the example seems to make a match?

**Comment by kingthorin** [comment]
Does anyone else have any input on this?

As the OP provided nothing further, and this could not be handled via Context Alert Filters, I believe it is safe to close.

Trying to pre-define a collection of strings to look for proximal to a IP regex match seems very error prone to me.

https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsAlertFiltersAlertFilter
