### ISSUE TITLE
Add -Xdock:name=ZAP to Mac Java startup options

### ISSUE THREAD

**Issue by veggiespam** [zaproxy/zaproxy#1797]
The Mac version of Java allows -Xdock:icon=file.icns to add an icon to the Dock; ZAP implements this now.  The "java -X" will show another option, -Xdock:name which enables the Dock mouse-over name to be something more useful than the word "java", ZAP does not use this.  I propose we add it to in $git/zaproxy/build/mac_os_x/OWASP ZAP.app/Contents/Info.plist.

This will make the Dock say "ZAP" instead of "java" as it does now for OS X 10.5 through 10.8.  

Unfortunately, in 10.9 / 10.10, either OS X or Java broke this.  See more https://bugs.openjdk.java.net/browse/JDK-8029440 and https://bugs.eclipse.org/bugs/show_bug.cgi?id=381970 for more thoughts on this topic.  I would still like to add -Xdock:name to the OS X start up since 1) many folks still use 10.8 in low-footprint testing VMs and 2) either OS X or future-Java may fix this bug (thus it will magically start working in ZAP).

**Comment by marumari** [comment]
I think these had actually been set long ago, but when that version of OS X, and Java became unsupported, I changed the code to set it in the only way that works on current versions of both:

https://github.com/zaproxy/zaproxy/blob/develop/src/org/zaproxy/zap/ZAP.java#L281

Note that there are other options we can set this same way:

-Dapple.laf.useScreenMenuBar=true
-Dcom.apple.macos.use-file-dialog-packages=true
-Dcom.apple.macos.useScreenMenuBar=true
-Dcom.apple.mrj.application.apple.menu.about.name=OWASP ZAP
-Dcom.apple.smallTabs=true
-Dfile.encoding=UTF-8

But they all (I believe) get completely ignored by the current versions of Java available, on modern OS Xs.  I doubt that it will ever get fixed in Java though, since ZAP is currently doing things the supported way.

**Comment by veggiespam** [comment]
I just launched ZAP 2.3.1 which has jdk 1.7.0-51 embedded on OS X 10.5.5 and it does set the Dock Mouse-Over Title properly.  Java version issue I guess.

Thanks for showing me the line of code, ZAP is already doing the equivalent of the -X option properly.  I guess this bug should be renamed, "whenever Apple and Oracle figure Dock-Name out, do what they tell us."

**Comment by marumari** [comment]
ZAP 2.3.1 actually used a (long-abandoned) shim; it would launch an OS X 
app called JavaAppLauncher, which would be set to have a dock name of 
ZAP, which would then launch ZAP itself.

We wanted to get away from hosting random binaries inside our 
repository, especially unmaintained ones.  But that’s why you’re 
seeing this issue: because we’re now launching Java directly, instead 
of via an intermediary.

**Comment by kingthorin** [comment]
Is this issue still relevant?

**Comment by april** [comment]
I think it can probably be closed.
