### ISSUE TITLE
Forced browse: add request count

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#1873]
Or some other indication thats its actually doing something, like a pretty chat of response times ;)
As per https://twitter.com/troyhunt/status/640788055566086144

**Comment by mario-areias** [comment]
Just to clarify. The idea is to display the requests in a simple manner. Do you want to add only the response count? Or we want to have something more like this:
![activescan](https://cloud.githubusercontent.com/assets/1810284/9735286/095ba84c-567d-11e5-9282-7a493796a0f1.jpg)

**Comment by thc202** [comment]
I think this issue is just to add a counter of requests sent (like the "Active Scan" tab shows in the tool bar with "Num requests:").
If it is to show all requests (as opposed to just crawled or potential issues) it would be #559.

**Comment by mario-areias** [comment]
Cool. Will do that then :)

**Comment by mario-areias** [comment]
Okay. I was looking to see how to do this. After some though, I came up with two possible implementations:

1) Add a method to the `Manager class` called `notifyRequestSent`, something like:
```
private synchronized void notifyRequestSent() {
       count++;
}
```
Then in the `Worker class` I would add `manager.notifyRequestSent()` inside the `makeRequest` method.

The pros for this implementation are simplicity and clearness. However, this operation would block the threads when calling this method and it could have a major impact in performance.

2) Another approach would be implement the `notifyRequestSent` in a different way, using a [non-blocking queue](http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentLinkedQueue.html) like that:

```
private synchronized void notifyRequestSent(Request request) {
       queue.offer(request);
}
```
Then to get the number of requests it is just get from `queue.size()`. 

The pros of this way is to not having threads blocked by notifying request and also it a possible solution for #559 since we can store the request itself to display it afterwards. The con is that a solution a little more complicated and it would require more time to implement it.

What are your thoughts on that? Does that makes sense for you? Is there a better way to do this?

**Comment by kingthorin** [comment]
I'm not familiar with the code in question, however, from my PoV the second choice is better. As for it being slightly more complicated that's not necessarily a bad thing, especially if the code is well documented/commented.

**Comment by psiinon** [comment]
I think it would be good to implement something that makes it easier to support #559 even if we dont support it right now :)

**Comment by mario-areias** [comment]
Thanks @kingthorin and @psiinon I will start with the second option then :)

Just another cons from the second option is that the size method won't be very accurate while items are being added to the queue. It will be accurate after all items are added, so I think it is a minor issue. 

The other issue is that to do the size it requires a traversal which means it won't be a constant time operations, it will be a O(n) operation. In theory, it shouldn't impact that much, but I will monitor the performance as I go.

**Comment by thc202** [comment]
I agree as well on the second proposal (i.e. provide means to obtain the messages sent) although I've some concerns about the implementation:
 - Client code will have to actively query `Manager` class to know the number of messages sent (which might lead to another thread contending for resources?);
 - Message contents are kept in memory indefinitely, even if not needed. This is a major issue, given how many messages are sent in normal use cases.

How about letting interested parties (client code) register themselves to receive the "sent" notifications?
It would require (some) synchronisation (either by client code or `Manager` class) but client code would no longer need to actively query `Manager` class to know the number of messages sent (it would need to keep the count itself, though) and it would move the burden of the handling of the messages to client code (so the messages could be (persisted and) shown or simply ignored).

**Comment by mario-areias** [comment]
Hum, I got curious when you say client. I was assuming we will have only one, are we gonna have more clients consuming this information? If that's the case it makes things more complicated :/. 

About keeping messages in memory, I don't know if there is a way to solve it. The #559 tickets is related to show all requests on the panel. So the messages need to be in memory somewhere. Either on `Manager` class or any client class. Do you have any idea how many are they in average? If there are too many[1] we would have to filter the messages displayed on the panel

[1] Too many is subjective. I would say for the queue too many are several thousands messages, but for user experience display several thousands of messages is probably bad

**Comment by kingthorin** [comment]
I'm getting a bit off topic here, but, for 559 and populating the table. It could be statically set (like the active scan history) to 1000 entries. Or even better a generic FIFO representation of the traffic could be used in the panel(s) [i.e.: display only the 1000 most recent requests for the relevant component...Active Scan, Forced Browse, etc.]

**Comment by thc202** [comment]
@mario-areias well, we might, not (likely) at the same time though. [1]

The behaviour of most components is to persist the messages to DB (disk) and just keep the essential in memory (through `HistoryReference`). The full message is just loaded to display in Request/Response tabs, when selected.
No, it really depends on what file is used (`directory-list-1.0.txt` has more than 100k but `Apache.fuzz.txt` has just 42) and also if file extensions are set.

@kingthorin or paginate the results ;) but yeah, a FIFO should do it.

[1] https://github.com/hacktics/good-old-files/blob/33d4e52e8022836e36c4a48330abcd9004cf635f/releases/v1.0/source-code/GoodOldFiles.java

**Comment by mario-areias** [comment]
Thanks for the info @thc202! But do we need to persist this information in file system? Is there a requirement for that? I am asking that because I am pretty concerned with how much IO operations we will have to do and the impact in performance. 


I like the solution proposed by @kingthorin. Display the last n resources, so we don't keep everything in memory and don't need to have any IO operations as well. However, I will have to use something else to count. Probably using AtomicInteger.

**Comment by mario-areias** [comment]
Nice discussion, btw :)

**Comment by thc202** [comment]
The messages need to be persisted because they can't be kept in memory, that's the only reason.
If the messages are kept in memory, even if it's just for 1000 or so, ZAP might end up in OOME (it's enough with a couple of big messages). Of course, we could use `SoftReference`s but it might happen that the user wants to inspect a message and it's no longer available.
Something that needs to be discussed in more depth for #559.

**Comment by mario-areias** [comment]
After this thread (pun not intended :P) I was reviewing how the synchronization works for DirBuster and it is actually pretty complicated. The `Manager` class has 3 queues which is used in, basically, 3 different threads `Worker`, `HTMLParser` and `WorkGenThread` (there is actually 4 ou 5 types of this one). Each thread actually changes 1 or more queues, so any change here can be a problem :( 

Also, these queues are initialised with really huge numbers as viewed here:

https://github.com/zaproxy/zap-extensions/blob/beta/src/com/sittinglittleduck/DirBuster/Manager.java#L518

So we already have lots of stuff in memory, although I don't know (yet) if we are using that much of space in the queues. I am trying to work on some refactoring to make things more simple, but yet not changing any behavior. So I can change things slowly and measure the impact of any change. I am not entirely convinced that persist the message is the way to go, I am a little concerned about the impact on the performance of so many requests doing IO operation. 

Anyway, I will get some data and we can discuss further :)

**Comment by mario-areias** [comment]
My PR to this issue has been merged. Do we need to close that? Or is there anyone testing it to make sure?

**Comment by mario-areias** [comment]
@psiinon @thc202 sorry to be annoying. But I am not really sure what to do with this issue. Should we close it? Assign to someone else to test it?

**Comment by thc202** [comment]
Sorry! Yeah, this should be closed, it should have been closed automatically but since it was merged to a non default branch it was not... :/
(the changes were tested before being merged ;)
