### ISSUE TITLE
Testing specific OWASP vulnerabilites using ZAP

### ISSUE THREAD

**Issue by ambikashri** [zaproxy/zaproxy#1882]
Active Scanning can find many OWASP vulnerabilities. Is there a way to find out that if I do certain type of active scanning it will find A1 vulnerability some other type then it detects A2 vulnerability?? 
Same way with Spidering or any other feature of ZAP. I am asking this because this would help me to write scripts specific to OWASP Top 10  vulnerabilties rather than based on ZAP features.For e.g., A1 vulnerabilty can be detected using
Active Scanning and Fuzzer. So I write a script for A1 wherein I combine certain features available in Active Scanning to detect A1 vulnerabilty and the same with Fuzzer.

**Comment by psiinon** [comment]
I'm actually not that keen on the OWASP Top 10 as a way of categorizing vulnerabilities.
In my mind its an education document rather than a form of classification.
You cant automatically detect all of the Top 10, as I mention on https://www.owasp.org/index.php/ZAPpingTheTop10
And the whole thing about 'manual' tools in ZAP is that they are manual - they're not really scriptable as they need a human to direct them and interpret the results.
So other than mapping alerts to the Top 10 (as per  #1879) I'm not really sure what we can do here :/
But suggestions gratefully received :)

**Comment by psiinon** [comment]
Just referenced this issue here: https://groups.google.com/d/msg/zaproxy-develop/McCDEblUE88/Rk01X-4aDwAJ

**Comment by kingthorin** [comment]
Is there some outstanding related to this or can it be closed?

**Comment by kingthorin** [comment]
Closing due to lack of feedback. Plus https://github.com/zaproxy/zaproxy/issues/1879 is strongly related if not somewhat duplicate.
