### ISSUE TITLE
ZAP cant completely scan OWASP Benchmark

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#1890]
ZAP scores pretty badly against OWASP Benchmark :(
https://rawgit.com/OWASP/Benchmark/master/scorecard/Benchmark_v1.2beta_Scorecard_for_OWASP_ZAP.html
To start with this is because ZAP cannot complete a full active scan of the app (which is huge).
Not sure why yet, but it could be locking, db issues etc etc. It may be non trivial to fix this, so detailed knowledge of the ZAP internals might be necessary to solve this issue.
After that we should look at any rules that arent performing as well as we think they should - Benchmark is quite particular in how it tests scanners :/
But this issue just covers getting ZAP to perform a complete active scan of OWASP Benchmark with all of the default scan rules enabled.

**Comment by kingthorin** [comment]
Note:
https://www.owasp.org/index.php/Benchmark#tab=FAQ
> For example, we were not able to successfully scan the 1.2beta with OWASP ZAP with only 8 Gig of RAM.

**Comment by ElColmo** [comment]
One reason I could see offhand is that some of the test cases (https://localhost:8443/benchmark/BenchmarkTest00008.html, for instance) send a custom request header ("vector" is used in this case).  Zap, however, does not scan this header, even with the "HTTP Headers" input vector enabled.  This appears to be due to the following code in org.parosproxy.paros.core.scanner.VariantHeader:

    public static final String[] injectableHeaders = {
        HttpRequestHeader.USER_AGENT,
        HttpRequestHeader.REFERER,
        HttpRequestHeader.HOST
    };

In other words, only these 3 headers are ever attacked by default.

For this specific example, if you specify a custom attack vector, and ensure that the "SQL Injection - Hypersonic" scanner is enabled, the issue is successfully detected and alerted.  The "Advanced SQL Injection" scanner does not detect the SQL Injection issue, for some reason.

If you want, I can raise a separate issue for this header-scanning issue.

**Comment by psiinon** [comment]
Yeah, I noticed that too, and meant to raise an issue.
In this case I was wondering if we should use a blacklist instead of a white list.
I think its worth raising this, and any other limitations in ZAPs scanning exposed by Benchmark, as separate issues, as they can be addressed independently.

**Comment by ElColmo** [comment]
I've raised it: https://github.com/zaproxy/zaproxy/issues/1894.

**Comment by ElColmo** [comment]
What procedure are you following to scan this app in ZAP, by the way? I don't see a documented process for scanning it with ZAP.  It would be good for us to agree on the basics, before any detailed analysis/discussions take place.

**Comment by psiinon** [comment]
We're starting with simple 'Quick' scans via the UI, so traditional spider then active scan.
First pass will be just using the std release.
Once that works include the beta and then alpha rules.
And try the Ajax spider too to see if that helps.
FYI I'm using ZAP project funds to pay @thc202 to work full time on this this week.
His first focus is getting ZAP to complete the scan, ie scalability.
After that he's going to look into how we can (reasonably) improve the scores (ie good improvements to the code, not ones just to improve the scores).
But definitely appreciate other people looking at Benchmark, esp re the rules which dont score as well as we think they should!

**Comment by ElColmo** [comment]
That's fine by me. 

Is there a script set up already to attack in the manner you describe, by any chance? :)

**Comment by psiinon** [comment]
I have basic AWS / Docker scripts for setting up Benchmark and ZAP if they would help?

**Comment by ElColmo** [comment]
I have both of those running already (although it took a bit of fiddling to realise that the Maven version installed on Kali wouldn't compile Benchmark).  I meant a script to scan Benchmark using ZAP, assuming both were already set up. I was being a bit optimistic, to be honest!

**Comment by ElColmo** [comment]
I'm in the process of automating some of the testing, on a scanner by scanner basis, against Benchmark (or other benchmarks).  A few things I've noticed:
- Some Benchmark test cases do not work, due to exceptions being thrown by the Benchmark code itself (class not found), before the attack even commences.  These cases can never be successfully detected by ZAP, or any dynamic scanner, for that matter.  I've raised the issue upstream.  Keep an eye on the Benchmark logs to see if this issue affects you.
- The HyperSonic db used by Benchmark gets corrupted quite quickly when attacked with any of the SQL Injection scanners, making the platform subsequently unusable, even when not under attack.  I've raised the issue upstream, and requested a lightweight means of "resetting" the database periodically (such as by making a POST request).
- The Benchmark app (running in its default installation) runs in a highly insecure dedicated Tomcat 8 installation (admin user with no password, various console webapps exposed on all interfaces). For the sake of the security of your test rigs, I suggest you make sure your host-based firewalls block port 8443 inbound.
- The Ajax Spider must be run (in addition to the "classic"/"old skool" spider), to detect a number of the vulnerabilities.
- A number of the scanners need to be set to "High" attack strength to detect the vulnerabilities.
- URL parameters, POST parameters, headers (using the updated logic), and cookies must be attacked, to detect some of the vulnerabilities.

**Comment by psiinon** [comment]
Thanks - thats really useful!
Ricardo has also been looking into some ZAP performance issues, including memory leaks and ZAP db tuning.
@ElColmo : does the Path Traversal rule find any issues at High strength? They score it at zero :( They also score LDAP at zero, but thats in the beta rules that they might not have used..

**Comment by ElColmo** [comment]
@psiinon I haven't gotten as far as that yet (and probably won't over the next few days, to be honest), but I'll keep it in mind. I'd be surprised if neither the Path Traversal or LDAP Injection found anything though.  I've tested both in various configurations in test apps, and in the wild, and they've both produced useful results.  

I want to get some of the basics established before I spend time on scanners other than the one I'm currently looking at, in order to try to minimise having to re-visit testing after changes to the core, and the Benchmark.

I'm also focussing on getting more true positives first, before worrying about the false positives. It's a big task to run each scanner against each of the test areas within Benchmark.  It's useful that @thc202  is looking more at the core, because that's complementary.

One other issue that came out of my analysis so far is that the Active Scan tab and the active scan popup window don't accurately reflect the actual number of request sent by the active scan, since they do not include requests that were actually sent, but which timed out (based on the timeout setting).  That tripped me up for a bit, since some active scans appeared to be completely locked up, but wireshark and netstat suggested something was going on behind the scenes, which prompted me to dig into it a bit more.  This was caused by the issue I mentioned earlier, where Benchmark requests for specific URLs gets un-responsive after SQL Injection attacks.

more peculiarities in ZAP:
- An Ajax scan initiated using the API  does not show in the status bar in the GUI (the only indication that it's happening is the Firefox / Iceweasel window popping up, it seems)
- Requests sent by the Ajax spider (when run manually, rather than via the API, at least) do not appear in the History tab, for some reason.  If you want to active scan one of these requests, you need to first right-click the request in the Ajax spider tab, click "Find in sites tree", right-click that node, and active scan that.  It's clumsy (given that I normally select requests in the history).

**Comment by psiinon** [comment]
Reopening this to cover scanning performance improvements.
And so that I can increase the bounty to cover a weeks work on this:)

**Comment by ElColmo** [comment]
The HSQL driver's "Connection.prepareStatement()" method in Benchmark hangs/takes ages after some scanning as well, making some URLs completely non-responsive after scanning has taken place.  More detail in https://github.com/OWASP/Benchmark/issues/10.  This is completely aside from the issue of the db tables getting corrupted by SQL Injection payloads.  Obviously not a ZAP issue, but should inform how we interpret the results we see in ZAP.

**Comment by thc202** [comment]
ZAP is now able to fully scan OWASP Benchmark (with just 512MiB of heap memory), the active scanner was able to send ~2M requests without problems.
With 2.4.2 it would fail with OOME (around 450k requests).

Following test results with ZAP built from `develop` branch, with normal (and AJAX) spider, with and without appropriate input vectors enabled (i.e. HTTP headers (including "vector" header), Cookies) and all add-ons bundled with version 2.4.2.

Running just the normal spider without enabling appropriate input vectors:

| Category | TP | FN | TN | FP | Total | TPR | FPR | Score |
| ------------- | ---- | ---- | ---- | ----- | ------ | ------ | ------ | -------- |
| Command Injection | 44 | 82 | 125 | 0 | 251 | 34.92% | 0.00% | 34.92% |
| Cross-Site Scripting | 71 | 175 | 209 | 0 | 455 | 28.86% | 0.00% | 28.86% |
| Insecure Cookie | 36 | 0 | 31 | 0 | 67 | 100.00% | 0.00% | 100.00% |
| LDAP Injection | 0 | 27 | 32 | 0 | 59 | 0.00% | 0.00% | 0.00% |
| Path Traversal | 0 | 133 | 135 | 0 | 268 | 0.00% | 0.00% | 0.00% |
| SQL Injection | 96 | 176 | 232 | 0 | 504 | 35.29% | 0.00% | 35.29% |
| Trust Boundary Violation | 0 | 83 | 43 | 0 | 126 | 0.00% | 0.00% | 0.00% |
| Weak Encryption Algorithm | 0 | 130 | 116 | 0 | 246 | 0.00% | 0.00% | 0.00% |
| Weak Hash Algorithm | 0 | 129 | 107 | 0 | 236 | 0.00% | 0.00% | 0.00% |
| Weak Random Number | 0 | 218 | 275 | 0 | 493 | 0.00% | 0.00% | 0.00% |
| XPath Injection | 0 | 15 | 20 | 0 | 35 | 0.00% | 0.00% | 0.00% |
| Totals | 247 | 1168 | 1325 | 0 | 2740 | 18.10% | 0.00% | 18.10% |

This results should be the same as the ones [reported in OWASP Benchmark site](https://rawgit.com/OWASP/Benchmark/master/scorecard/Benchmark_v1.2beta_Scorecard_for_OWASP_ZAP.html) (with the exception of "SQL Injection" which performed better).

Running with appropriate input vectors and AJAX spider leads to more findings (some of the tests require client side interaction):

| Category | TP | FN | TN | FP | Total | TPR | FPR | Score |
| ------------- | ---- | ---- | ---- | ----- | ------ | ------ | ------ | -------- |
| Command Injection | 46 | 80 | 125 | 0 | 251 | 36.51% | 0.00% | 36.51% |
| Cross-Site Scripting | 207 | 39 | 207 | 2 | 455 | 84.15% | 0.96% | 83.19% |
| Insecure Cookie | 36 | 0 | 31 | 0 | 67 | 100.00% | 0.00% | 100.00% |
| LDAP Injection | 0 | 27 | 32 | 0 | 59 | 0.00% | 0.00% | 0.00% |
| Path Traversal | 0 | 133 | 135 | 0 | 268 | 0.00% | 0.00% | 0.00% |
| SQL Injection | 104 | 168 | 205 | 27 | 504 | 38.24% | 11.64% | 26.60% |
| Trust Boundary Violation | 0 | 83 | 43 | 0 | 126 | 0.00% | 0.00% | 0.00% |
| Weak Encryption Algorithm | 0 | 130 | 116 | 0 | 246 | 0.00% | 0.00% | 0.00% |
| Weak Hash Algorithm | 0 | 129 | 107 | 0 | 236 | 0.00% | 0.00% | 0.00% |
| Weak Random Number | 0 | 218 | 275 | 0 | 493 | 0.00% | 0.00% | 0.00% |
| XPath Injection | 0 | 15 | 20 | 0 | 35 | 0.00% | 0.00% | 0.00% |
| Totals | 393 | 1022 | 1296 | 29 | 2740 | 23.54% | 1.14% | 22.39% |

The "Command Injection" reported two more TPs.
While "SQL Injection" reported more TPs it also reported FPs, leading to lower score.
It was also run with DOM XSS scanner that's why the (great) improvement of "Cross-Site Scripting" (and overall) results.

Worth noting that in all cases no "Path Traversal" vulnerabilities were reported (double checked with "Alerts" tab).

The [persistence properties of DB](http://www.hsqldb.org/doc/2.0/guide/management-chapt.html#mtc_cache_persistence) used by ZAP were slightly changed to (try) improve the speed of the scans.
One of the properties that had more noticeable results was the disable of log. No more unnecessary checkpoints and backups, which improved the time of the scans and number of requests sent per second. The drawback is that it could lead to data loss, but not a problem when running the benchmarks.

Note: I used a modified version of OWASP Benchmark for all the tests because it was giving some issues that prevented it from working properly (change already submitted in a PR).

@ElColmo I'm not seeing the "class not found" errors, it says:
```
[INFO] Press Ctrl-C to stop the container...
[INFO] [talledLocalContainer] DataBase tables/procedures created.
```
Is that happening always? Maybe that's what's causing the issue(s) with database?
Which SQLi scanner(s) is breaking the DB?

Indeed, the active scanner is not updating the number of requests sent in case of errors, I'll take a look at that.
The AJAX spider was not yet updated to show the API scans in the GUI.
That's an issue, the requests should be associated with the node. It shows the requests in "AJAX Spider" tab instead of "History" because that's how all components work (each one shows the results in its own tab).

**Comment by ElColmo** [comment]
Very interesting results.  Have you collated that info manually?

Yes, I get that same error every time I restart Benchmark (after startup).
It affects some of the tests, but not all, since the test case code uses a
couple of different idioms.  Specifically, it occurs when the
DatabaseHelper is first loaded by a test case.

[INFO] [talledLocalContainer] Tomcat 8.x started on port [8443]
[INFO] Press Ctrl-C to stop the container...
...
[INFO] [talledLocalContainer] Problem with database table/procedure
creations: Error creating bean with name 'dataSource' defined in class path
resource [context.xml]: Instantiation of bean failed; nested exception is
java.lang.NoClassDefFoundError:
org/apache/commons/pool/impl/GenericObjectPool
[INFO] [talledLocalContainer]
org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'dataSource' defined in class path resource [context.xml]:
Instantiation of bean failed; nested exception is
java.lang.NoClassDefFoundError:
org/apache/commons/pool/impl/GenericObjectPool
[INFO] [talledLocalContainer] at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1101)
...
[INFO] [talledLocalContainer] at java.lang.Thread.run(Thread.java:745)
[INFO] [talledLocalContainer] Caused by: java.lang.NoClassDefFoundError:
org/apache/commons/pool/impl/GenericObjectPool
[INFO] [talledLocalContainer] at
java.lang.Class.getDeclaredConstructors0(Native Method)
...

Other database issues I'm still seeing are below. By their nature, these
issues occur depending on the attacks that have taken place (using the
Hypersonic SQL Injection scanner), and how long the Benchmark instance is
running.
- successful SQL Injection payloads apparently clearing down data, so some
URLs return no data for the base case.
- The HSQL driver's Connection.prepareStatement() method is locking up
(possible SQL Injection vulnerability in the JDBC driver itself??)

I'm only using (a slightly modified) version of the HSQL scanner to cause
these issues.  I'll release this modified version back as soon as I can get
a solid run, where the Benchmark, and where the score percentage is
reasonable.  I think its time for me to fetch your changes!  I'm very much
doing this work in the background, so this is not currently my main focus.

Colm
