### ISSUE TITLE
ZAP should ensure response in base message before passing them to scanners

### ISSUE THREAD

**Issue by denniskniep** [zaproxy/zaproxy#1964]
The base message in scanners might not contain a response (getBaseMsg().getResponseHeader().isEmpty() returns true), which will lead to FPs.

ZAP should ensure that the messages have a response before passing them to scanners. If not it should send a new request and use that as base message.

Noticed in pull request https://github.com/zaproxy/zap-extensions/pull/47 by @thc202 (see https://github.com/zaproxy/zap-extensions/pull/47#discussion_r41240218)

If the issue is fixed it would be recommandable to ensure that all active scanners won't do the same check (i.e. https://github.com/zaproxy/zap-extensions/blob/bbbba9bbaa5fd979f2a0b1e04cb33f5680775ac3/src/org/zaproxy/zap/extension/ascanrulesAlpha/TestUserAgent.java#L127)

**Comment by psiinon** [comment]
Do you have any examples where this happens?

**Comment by thc202** [comment]
The messages with empty responses are the "temporary" messages created for the Sites tree. An example that would lead to FP is the scanner TestUserAgent since it was comparing the responses using the base message, although there are other scanners [1]\(?) [2] that are sending the original request to obtain the response (which shouldn't as that might modify the original request).
The passive scanner ignores the temporary messages, maybe it should happen the same with active scanner? The user would have to explicitly access those pages to have them scanned though.

[1] https://github.com/zaproxy/zap-extensions/tree/1aea8538f7fb207d62015faef731cfdac1de21cd/src/org/zaproxy/zap/extension/ascanrulesAlpha/SlackerCookieDetector.java#L46-L51
[2] https://github.com/zaproxy/zap-extensions/tree/1aea8538f7fb207d62015faef731cfdac1de21cd/src/org/zaproxy/zap/extension/ascanrulesAlpha/SourceCodeDisclosureFileInclusion.java#L213-L214

**Comment by psiinon** [comment]
OK, that explains it.
So we've never had responses to these requests.
Some options:
* Automatically request such pages when adding them to the tree (which I really dont like;)
* Automatically request such pages prior to active scanning (much more acceptable)
* Not active scanning these pages
* Adding an option to not scan these pages (not keen on that either)
* Ensuring all rules can cope with null responses (which is kind of what we should be doing now)
Any preferences, or alternative suggestions?

**Comment by thc202** [comment]
I'd opt for "Not active scanning these pages".

**Comment by psiinon** [comment]
What would the impact of this be?
The only thing I can think of offhand is if someone scanned a 'temporary' page and chose not to recurse. Right now all of the AbstractHostPlugins and AbstractAppPlugins run. With this change I think nothing would happen - is that right? That might be confusing for some people, especially if they wanted to check things like a site certificate.

**Comment by thc202** [comment]
Agreed, lets try to obtain the response prior the actual scan.
