### ISSUE TITLE
ScanningProxy IO Exception

### ISSUE THREAD

**Issue by Selenium-hari** [zaproxy/zaproxy#1983]
Hi,

I am currently facing two issues.

Unable to start a new session by using zapScanner.clear() provided in the example. Code is working only when ZAP is launched on desktop and a new session is manually initiated. 
Also, API key value needs to be passed from Zap-Preferences--> API as input to the    zapScanner = new ZAProxyScanner(ZAP_PROXYHOST,ZAP_PROXYPORT,ZAP_APIKEY);

Else, scanWithZap(); kind of functions are throwing IO exception.

Can some help be provided on how to get the new session initiated and is there a way to retrieve the API key once the session has been initialized, pls.

**Comment by thc202** [comment]
FAQ contains instructions on how to set (or even disable) the API key through the command line:
https://github.com/zaproxy/zaproxy/wiki/FAQapikey

The IO exceptions are most likely related to missing/wrong API key. I guess the clear() method is failing because of the same issue.

Which version of ZAP are you using? And zap-java-api?

**Comment by Selenium-hari** [comment]
Yes, i got the issue resolved. Thanks

**Comment by thc202** [comment]
Thanks for letting us know.
