### ISSUE TITLE
Results when spider one sites

### ISSUE THREAD

**Issue by valour01** [zaproxy/zaproxy#2434]
I noticed that when I use the spider to scan a target site. The results are different among every scan. May I know the reason why the results are different. And the changing value is always the dynamic resource  like the `jsessionid`. 

Another thing is that I noticed in a scan result. When I analysis the full result I find there may be two same urls using `POST` method with different content-length. Is it available to see the content. I mean the detail difference (maybe the post forms) between the two URLs. Many Thanks

**Comment by thc202** [comment]
By default the spider does not use any session (cookies), that's why the session ID ends up being added to the URLs.
To prevent that you can set a session as active.

Using the ZAP API you can obtain the request bodies with the `message` API view (field `requestBody`), then diff the bodies "manually".
If you are using the GUI you can diff the requests/responses using the Diff add-on. (Also, with latest weekly releases you can see the messages sent in the Spider tab which makes it easier to find and diff them.)

For questions about ZAP usage, like these, is better to use the users mailing list than raise an issue.

**Comment by valour01** [comment]
@thc202 I see. Thanks for your reminding. I am sorry that I will use mailing list next time for ZAP usage. However, I  guess you may not capture my point this time. What I mean is 
>POST  http://127.0.0.1:8080/jpetstore/actions/Catalog.action;jsessionid=03BCDED6301A810A1286C6DBDC186A3F HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
Pragma: no-cache
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Content-Length: 226
Referer: http://127.0.0.1:8080/jpetstore/actions/Catalog.action;jsessionid=03BCDED6301A810A1286C6DBDC186A3F?categoryId=DOGS&viewCategory
Host: 127.0.0.1:8080

I can see the `content-length` and `content type` in the request headers. But what I want (the missing part in question 2414) is that what actually do we post. I mean the key-value pair when we post the request. It seems I can not get it in the request header. BTW: All the things I mean are about ZAP API rather than GUI tool.

**Comment by thc202** [comment]
How did you obtain that request header? Was it with the `message` view? That also returns the request body (it contains the header/body pair for both the request and response).

**Comment by valour01** [comment]
@thc202 Got it. Many Thanks

**Comment by thc202** [comment]
@valour01 you're welcome!
