### ISSUE TITLE
Lack of menu entry and icon in Debian package

### ISSUE THREAD

**Issue by anantshri** [zaproxy/zaproxy#2500]
We don't have icons in .deb file and neither we have  menu entry. so even after installing the package its not creating a meu entry.

ICON
![owaspzap.png](https://cloud.githubusercontent.com/assets/236843/15448939/3fdde694-1f8d-11e6-93ae-05a805e68a71.png)

Menu Entry should go in usr/share/applications/

```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
TryExec=/usr/bin/owasp-zap
Exec=/usr/bin/owasp-zap
Name=OWASP ZAP
Icon=owasp-zap
Categories=Development
```

**Comment by psiinon** [comment]
What do we need where? Pull Requests always welcome :)

**Comment by rajiv65** [comment]
I have successfully edited the code in zap.sh which was in the zip file downloaded for linux from https://github.com/zaproxy/zaproxy/wiki/Downloads . It now asks the user if he wants to create a menu item entry and it successfully creates an icon when the user wants it. But I couldn't find the zap.sh file in the github repo so that I can edit it and open a pull request. I would be glad if you could help me in figuring out how to make changes to the linux zap.sh file so that it can reflect in the downloaded zip file . Thanks.

**Comment by thc202** [comment]
The file `zap.sh` is under the `src` directory. [1]

Is the script `zap.sh` the right place to add that? Shouldn't that be part of the deb package (somehow)?

[1] https://github.com/zaproxy/zaproxy/blob/5aa43e8bbb2d1ea4fff82cf7838f5f4041214d36/src/zap.sh

**Comment by anantshri** [comment]
I am trying to create a proper entry but i am away from work laptop and don't have zap build environment so my pull request will have to be double triple cross validated by someone else.
