### ISSUE TITLE
Unit tests for CSRFCountermeasures

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2801]
Create unit tests for the class: https://github.com/zaproxy/zap-extensions/tree/beta/src/org/zaproxy/zap/extension/pscanrulesBeta/CSRFCountermeasures.java
In the package: https://github.com/zaproxy/zap-extensions/tree/beta/test/org/zaproxy/zap/extension/pscanrulesBeta

Unit tests should test all of the associated functionality and include tests for false positives.
The tests should at least check the number of alerts and the parameters and evidence (as appropriate). Additional checks can be made if thought useful.
Tests for other rules can be found in https://github.com/zaproxy/zap-extensions/tree/master/test/org/zaproxy/zap/extension/pscanrules

**Comment by psiinon** [comment]
This issue is part of the ZAP Unit Test Bounty: http://zaproxy.blogspot.com/2016/08/announcing-zap-unit-test-bounties.html
Bounties will be paid only when the PR has been merged. The PRs must test all of the associated rule functionality and must conform to our Development Rules and Guidelines.

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/wiki/DevGuidelines#unit-test-specific-guidelines

**Comment by peterschuler** [comment]
I have created the test. How do I submit it?

**Comment by psiinon** [comment]
@peterschuler Great :) You need to submit a Pull Request to the repo: https://help.github.com/articles/creating-a-pull-request/

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#570.

**Comment by thc202** [comment]
@peterschuler you should be able to claim the bounty in:
https://www.bountysource.com/issues/37164938-unit-tests-for-csrfcountermeasures

**Comment by psiinon** [comment]
@peterschuler I'm assuming you've just submitted your claim, but just double checking here to make sure :)

**Comment by peterschuler** [comment]
it was me. Thanks for al the rework guys.

**Comment by kingthorin** [comment]
@peterschuler could you let us know how you'd like to be added to the credits?
https://github.com/zaproxy/zap-core-help/wiki/HelpCredits#zap-extended-team

**Comment by peterschuler** [comment]
Peter Schuler will work for me.
-------- Oorspronkelijk bericht --------Van: kingthorin <notifications@github.com> Datum: 03-05-17  11:47  (GMT+01:00) Aan: zaproxy/zaproxy <zaproxy@noreply.github.com> Cc: peterschuler <peter.schuler@gmail.com>, Mention <mention@noreply.github.com> Onderwerp: Re: [zaproxy/zaproxy] Unit tests for CSRFCountermeasures (#2801) 
@peterschuler could you let us know how you'd like to be added to the credits?

https://github.com/zaproxy/zap-core-help/wiki/HelpCredits#zap-extended-team

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/zaproxy/zaproxy","title":"zaproxy/zaproxy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/zaproxy/zaproxy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kingthorin in #2801: @peterschuler could you let us know how you'd like to be added to the credits?\r\nhttps://github.com/zaproxy/zap-core-help/wiki/HelpCredits#zap-extended-team"}],"action":{"name":"View Issue","url":"https://github.com/zaproxy/zaproxy/issues/2801#issuecomment-298866792"}}}

**Comment by peterschuler** [comment]
But I am already there 😊
-------- Oorspronkelijk bericht --------Van: kingthorin <notifications@github.com> Datum: 03-05-17  11:47  (GMT+01:00) Aan: zaproxy/zaproxy <zaproxy@noreply.github.com> Cc: peterschuler <peter.schuler@gmail.com>, Mention <mention@noreply.github.com> Onderwerp: Re: [zaproxy/zaproxy] Unit tests for CSRFCountermeasures (#2801) 
@peterschuler could you let us know how you'd like to be added to the credits?

https://github.com/zaproxy/zap-core-help/wiki/HelpCredits#zap-extended-team

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/zaproxy/zaproxy","title":"zaproxy/zaproxy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/zaproxy/zaproxy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kingthorin in #2801: @peterschuler could you let us know how you'd like to be added to the credits?\r\nhttps://github.com/zaproxy/zap-core-help/wiki/HelpCredits#zap-extended-team"}],"action":{"name":"View Issue","url":"https://github.com/zaproxy/zaproxy/issues/2801#issuecomment-298866792"}}}

**Comment by kingthorin** [comment]
Thanks. I think I searched username not first or last, my bad.

**Comment by peterschuler** [comment]
Never mind .. my previous contribution was very long ago.
-------- Oorspronkelijk bericht --------Van: kingthorin <notifications@github.com> Datum: 03-05-17  22:48  (GMT+01:00) Aan: zaproxy/zaproxy <zaproxy@noreply.github.com> Cc: peterschuler <peter.schuler@gmail.com>, Mention <mention@noreply.github.com> Onderwerp: Re: [zaproxy/zaproxy] Unit tests for CSRFCountermeasures (#2801) 
Thanks. I think I searched username not first or last, my bad.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/zaproxy/zaproxy","title":"zaproxy/zaproxy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/zaproxy/zaproxy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kingthorin in #2801: Thanks. I think I searched username not first or last, my bad."}],"action":{"name":"View Issue","url":"https://github.com/zaproxy/zaproxy/issues/2801#issuecomment-299030867"}}}
