### ISSUE TITLE
Support scanning multipart filename and content parameter

### ISSUE THREAD

**Issue by jx6f** [zaproxy/zaproxy#2965]
Active scan skips multipart filename and content testing.

The filename parameter often cause terrible vulnerabilities such as OS command injection, Path traversal(write access).
Also the content testing interface is necessary to [Unrestricted File Upload](https://www.owasp.org/index.php/Unrestricted_File_Upload) and known vulnerabilities such as [ImageTragick](https://imagetragick.com/).

We can test them by using the custom input vector when recursive scan option is off.
So, adding them to general input vector is very convenient.

**Comment by psiinon** [comment]
Strange, this should be supported.
Have you checked the 'Multipart Form-Data' box on the Options / Active Scan Input Vector screen?

**Comment by jx6f** [comment]
Yes, I have checked.
I debugged zaproxy, and I discovered the reason why.

1. `org.parosproxy.paros.core.scanner.AbstractAppParamPlugin` creates instance of  `org.parosproxy.paros.core.scanner.VariantMultipartFormQuery`.
1. VariantMultipartFormQuery parses a multi-parted HttpMessage and build parameter lists, [stringParam](https://github.com/zaproxy/zaproxy/blob/333974524e280274428d901ac385b3636c554c9d/src/org/parosproxy/paros/core/scanner/VariantMultipartFormQuery.java#L65) and [fileParam](https://github.com/zaproxy/zaproxy/blob/333974524e280274428d901ac385b3636c554c9d/src/org/parosproxy/paros/core/scanner/VariantMultipartFormQuery.java#L70).
1. AbstractAppParamPlugin#scanVariant gets stringParam parametere list [via VariantMultipartFormQuery#getParamList](https://github.com/zaproxy/zaproxy/blob/333974524e280274428d901ac385b3636c554c9d/src/org/parosproxy/paros/core/scanner/AbstractAppParamPlugin.java#L174) and executes scan.
1. However, VariantMultipartFormQuery#fileParam won't be get, because it is a private member and  a getter interface not implemented.

**Comment by kingthorin** [comment]
I've begun looking into this. I think it would take too much effort to rejig the existing Variant to work in both situations since the content replacement (param setting) functionality needs to be completely different for params vs file details. 

I'd like the leave the existing Variant as is, and add a new Variant (such as VariantMultipartFormFileDetails). Which can either be triggered anytime the existing multipart form variant is, or dependent upon a new option? The initial implementation will simply allow manipulation of the "fileName" pair (maybe the content type too?) Not the actual content of the file (as that's kind of a different beast too, and I think our existing active scanners don't target any file content injection [just injecting XSS, SQLi, command exec, etc replacing file content isn't likely to be successful]).

**Comment by kingthorin** [comment]
This is being worked on, see: https://github.com/zaproxy/zaproxy/pull/3814 for further details.

**Comment by thc202** [comment]
@kingthorin could this target 2.7.0?

**Comment by kingthorin** [comment]
I don't think I can get it done on time. I've gone down a path that has turned out not to work when multiple replacement strategies are needed. So now I've gotta come up with a completely new plan.

I'll try but I spent an hour or so last night without making any real progress. 

I guess we could go ahead with: https://github.com/zaproxy/zaproxy/pull/3814/files though that's only a baby step forward. It supports manipulation of filenames, but lacks support for manipulation of file param content or file param content-type.

**Comment by kingthorin** [comment]
Maybe you guys have suggestions. Where I'm finding it falls apart is when you need to handle one parameter multiple times (content, filename, content type).

Maybe it's better broken into multiple variants? (That's where the original/earlier PRs had been headed.) Unfortunately that seems to lead to lots of duplicate code, or not necessarily duplicate but repeated parsing of the same message... maybe I shouldn't be concerned on that front?

**Comment by thc202** [comment]
Fixed in #3814.
