### ISSUE TITLE
Redirect history not recorded when resend request

### ISSUE THREAD

**Issue by g-sato** [zaproxy/zaproxy#2989]
Hello zap team,

I found a problem about ZAP history log.

［Steps to reproduce］

1. Make these three php files, and put it on webserver.

[index.php]
```
<?php
header('Location: index2.php');
exit;
?>
```
[index2.php]
```
<?php
header('Location: index3.php');
exit;
?>
```
[index3.php]
```
<?php
phpinfo();
?>
```

2. Run ZAP 2.5.0 and access index.php

3. the URL history on ZAP history window is below:
```
GET index.php / 302 Found / 0kb
GET index2.php / 302 Found / 0kb
GET index3.php / 200 OK / 97.96KiB
(* 3 lines)
```
4. Do resend request to index.php by select "Resend.." in contextmenu of ZAP history window.

5. The URL history displayed on ZAP history window is below:
```
GET index.php / 200 OK / 98.16KiB
(* 1 line)
```
This history log is looks like there is a one response back from index.php as single page and there is no redirects.
(Additional information, same problem occurs in a part of activescan to index.php)

Is this the intended behavior?

Regards.

**Comment by kingthorin** [comment]
Did you have follow redirects enabled? (Green arrow in the resend toolbar)
Are any of the responses cached?

**Comment by g-sato** [comment]
> Did you have follow redirects enabled? (Green arrow in the resend toolbar)

Yes. I overlooked that button. Thank you for your answer.

But when resend request to index.php that sample program above  with "follow redirects" option enabled, the history record shuld be three requests I think. But now only one request appeared on history.Is this behavior cause misleading?

**Comment by kingthorin** [comment]
I'm guessing this is different because: 
- when it's proxied the browser is actually technically making 3 requests.
- when it's sent manually the apache http client takes care of the redirects and ZAP only "sees" the original request and final response.

Right?

So in order to overcome that we'd have to always set follow redirects false on the sendAndReceive but then check the state of the follow redirects button and if the response is a redirect then manually send the follow-up request(s)? (Checking for loops? Does any part of the core limit number of redirects?)

**Comment by thc202** [comment]
@kingthorin the `HttpSender` now allows to obtain all the redirections followed, it's just a matter of showing them (per #3741).

**Comment by thc202** [comment]
Regarding the original question:
> Is this the intended behavior?

Yes, that was the expected behaviour (since Paros days?).

**Comment by kingthorin** [comment]
@thc202 thanks
