### ISSUE TITLE
Problem to start the zaproxy

### ISSUE THREAD

**Issue by nitintajane1111** [zaproxy/zaproxy#3070]
when I start the OWASP I  found the pop window for "An error occurs while starting the proxy can't assign the requested address: JVM_Bind.
please give me solution to start the proxy service.

**Comment by psiinon** [comment]
This is likely to be because ZAP is configured to listen on port (by default 8080) that another application is already listening on.
You can change this via the relevant options page: https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsLocalproxy

Please ask questions on the ZAP User Group: https://groups.google.com/group/zaproxy-users
Issues should only be used for bugs or enhancement requests.
