### ISSUE TITLE
Generate Go library

### ISSUE THREAD

**Issue by micahhausler** [zaproxy/zaproxy#3281]
It seems based on #1938 that support for building a go library is possible, but currently [zaproxy/zap-api-go](https://github.com/zaproxy/zap-api-go) is empty. Can a library be generated?

**Comment by thc202** [comment]
It's still missing some code, that uses/exposes the generated code (AFAICT). It would be great if someone could help set up that.

**Comment by mqliang** [comment]
@thc202 I'd like to pick this up since I have a good knowledge of Go. However, when I try run "ant build -f build-api.xml", I unfortunately get some errors:

```
➜  build git:(scaner-dedup) ant -f build-api.xml
Buildfile: /Users/mqliang/Documents/Caicloud/src/github.com/zaproxy/zaproxy/build/build-api.xml

BUILD FAILED
/Users/mqliang/Documents/Caicloud/src/github.com/zaproxy/zaproxy/build/build-api.xml:19: taskdef class org.zaproxy.clientapi.ant.AccessUrlTask cannot be found
 using the classloader AntClassLoader[]

Total time: 0 seconds
```
Actually, I don't know how the client generation works. I look through the codebase, it seems  not OpenAPI. Could you please give me some instructions?

**Comment by thc202** [comment]
The Go generator is at:
https://github.com/zaproxy/zaproxy/blob/1b8ea631f514835eee02123dfc91d44ff1c427ca/src/org/zaproxy/zap/extension/api/GoAPIGenerator.java
(You just need to run that class.)

**Comment by mqliang** [comment]
Successfully generate the client code(see generated client here https://github.com/mqliang/zap-api-go/commit/af5e52e7c3a7c1378bb05e1308194a2e4c2de14c).

But if IIUC the client will ***NOT*** work. Since the generated client actually use some dummy struct to send HTTP request to ZAP server, and the most important "Request" method implementation is missing.  So, I think I should hand write a "Client" struct and implement a "SendRequest" for it:
```
type Client {
	Addr string
}

func (c *Client) SendRequest(path string, payload interface{}) {
	// marsh the payload as json and send HTTP request
}
```

And modify  the template like this:
```
type Acsrf struct {
	c *Client
}
// Lists the names of all anti-CSRF tokens
func (a Acsrf) OptionTokensNames() (interface{}, error) {
	return a.c.Request("acsrf/view/optionTokensNames/")
}

```
BTW, the exact HTTP method(PUT, GET, POST, DELETE) is also missing. How can I known which HTTP method to use when send request?

**Comment by thc202** [comment]
Correct, the generated code will not work by itself, it's missing some more code (that code should also allow to specify ZAP's address, port, and API key).

That implementation sounds reasonable to me (that's similar to other API implementations). The API expects GET requests (with query parameters), although we could send POST for the actions.
