### ISSUE TITLE
Accept underscores in hostnames

### ISSUE THREAD

**Issue by tomasji** [zaproxy/zaproxy#3284]
Having a browser configured to use ZAP as a proxy, the browser sends an HTTP (proxy) request like:
```
GET http://hive_test_00.example.com:30001/ HTTP/1.1
Host: hive_test_00.example.com:30001
User-Agent: Mozilla/5.0
```
ZAP tries to connect to http://hive_test_00.example.com/  on default **Port 80** instead of the requested **30001**
```
GET / HTTP/1.1
User-Agent: Mozilla/5.0
Host: hive_test_00.example.com
```

OWASP ZAP-2.5.0

**Comment by thc202** [comment]
That's caused by the underscores in the hostname. Anyway, ZAP should handle that better.

**Comment by derFunk** [comment]
I spent a lot debugging time on this as well yesterday, just to find out the underscore issue myself.

Are there any plans to maybe replace the Apache http client with another stack, like OkHttp? I know it would be a bigger deal because the API is not quite compatible, but maybe it's worth it?

Some good thoughts here: https://medium.com/square-corner-blog/okhttps-new-url-class-515460eea661
