### ISSUE TITLE
Windows: Missing extension in config file for <name> tag for scripts

### ISSUE THREAD

**Issue by JordanGS** [zaproxy/zaproxy#3304]
When creating a new script in windows. The extension is required as part of the name tag for the config file, otherwise an api exception will be thrown when trying to load the script.

Windows requires the extension
Linux requires that no extension is entered

The `<name>` in the config file directly referring to the Script name: when `creating/loading` a script.

As per IRC conversation, document the issue for now only.

As a 2.7.0 milestone, change the functionality of the `Script Engine:` drop down list to append an extension if it has not already been added to the `Script name:`. Ensure that the extension is only added if zap is running on windows an not on Linux.

**Comment by JordanGS** [comment]
@thc202 Does that about cover it?

**Comment by thc202** [comment]
I thought we were going to change the Jenkins plugin instead, to send the correct name?

Even changing ZAP, it's still a workaround, the Jenkins plugin might break again if the names are presented differently (also depending on defaults is still very fragile, error prone).

How about changing the Jenkins plugin to extract the actual names from the config.xml file (instead of enumerating the directory for scripts)?

**Comment by thc202** [comment]
Closing, now being handled in Jenkins issue tracker:
https://issues.jenkins-ci.org/browse/JENKINS-42911
