### ISSUE TITLE
PathTraversal rule performance issue

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3468]
https://github.com/zaproxy/zap-extensions/pull/515 changed the PathTraversal rule to make more requests.
Unfortunately these are now significantly outside of the recommendations :(
https://github.com/zaproxy/zap-extensions/blob/master/src/org/zaproxy/zap/extension/ascanrules/TestPathTraversal.java#L271-L302
It look like it can now make up to 28 reqs at Medium which is way over the 12 recommended, and in fact over the High level.
This is very apparent when scanning Bodgeit (as part of testing the weekly).
PathTraversal took 22 mins while the next longest (SQLi) only took 1:49 mins.
The total scan took ~ 30 mins, and thats with Release and Beta.
Having the option to make loads of requests is really good but we must have consistency.
We cant release the ascan rules with this change - @yhawke can you suggest how we can change this to fit in with the recommendations?
FYI the recommendations are on https://github.com/zaproxy/zap-extensions/wiki/AddOnsBeta:

- Low: up to around 6 requests / param / page
- Medium: up to around 12 requests / param / page
- High: up to around 24 requests / param / page
- Insane: whatever ;)

**Comment by yhawke** [comment]
Dear all, the trouble is related in the way the original PathTraversal plugin hasa been engineered and the combination of this with the issue thta has been set and solved with this implementation.
During a discussion made two years ago, the trouble was: "is possible to cut the number of tests for this plugin so that there could be some results but the quality still remains good enough?".
The problem is that if we check too low possibilities most of the newest Path Traversal vulnerability will not be found. We tested this using the Wavesep benchmark and to raise a good performance both on Java based or PHP based sites that were the number of checks that should be performed at medium and high level.
But due to the newest issue related to PathTraversal with directory access that number have been doubled because the same check should be performed with the Java, Windows, Linux and now with null postfixes.
I can rearrange the group of test to limit things according to the constraints but we'll then lack on plugin cases "coverage".

**Comment by yhawke** [comment]
Another thing that could be limited is the depth of ../ that can be appended to the Java/PHP standad files to find relative Path Traversal...

**Comment by psiinon** [comment]
I'm all for ZAP doing well against tests like Wavsep, but it shouldnt be at the expense of doing well against real world applications.
This means we shouldnt favor one type of test just to get a better score.
We have recommendations for the expected number of requests, we must stick to them.
I have no problem changing the recommendations but that must be agreed and applied to all rules.
Spending 2/3 of the scan time across all Release + Beta rules on one specific rule is just not justifiable.
If a user is particularly concerned about PathTraversal vulns then they can up the Strength just for that rule. We _cannot_ tune ZAP out of the box just to make it better against wavsep.

**Comment by yhawke** [comment]
This is exactly the point. Testing against Wavesep was the first step, then we tested on real cases and for this reason we incremented the number of checks to supply with the huge number of "possibilites" for this vulnerability. We can reduce the groups of tests to the most frequent ones and reamins under the constraints but we'll suffer by the fact that corrently the number of checks is strictly related to the underlying technology and by the issue previously set regarding the Path Traversal for directory content disclosure.
This means that this pugins currently is a combination of two tests: Path Traversal for direct File "access" and Path Traversal for directory disclosure.
Then both the two perform the same bunch of tests for the technology: Windows, Linux and Java tailored possibilities. This means that if the original set of tests is of 3 requests, the final number of requests is 3 x 3 + 3 = 12 checks...

**Comment by yhawke** [comment]
To remain under 6 requests we can check only for 2 patterns (8 total), for 12 requests we can check only 3 patterns (exactly 12), then for 24 we can test for 6 requests (exactly 24) which is more or less the number we have now for medium....
The patterns are usually with backslashes and slashes (so doubled again for each possibility) so we've to cut very strongly on the current implementation. If OK for all I can start to review it according to the frequency with these constraints.

**Comment by yhawke** [comment]
A possibility is to shift current strenghts (low -> medium, medium -> high), leave insane as it is and then create a low whith a more limited number of checks.

**Comment by psiinon** [comment]
+1 for that option :)

**Comment by yhawke** [comment]
Ok I'll do it in a while. Just a question, I suppose I've to raise a new pull request for this?

**Comment by psiinon** [comment]
Yeah, that ones been merged now :)

**Comment by kingthorin** [comment]
Essentially. Is there something we can do to help with that?

**Comment by yhawke** [comment]
Ok I've launched the pull request, please check if all the concepts map in the right way...

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zap-extensions/pull/867

**Comment by psiinon** [comment]
Interestingly the rule is still taking a lot longer than expected, even with the reduced number of requests. Myself and @thc202 are investigating. In the meantime the release quality ascan rules shouldnt be published until we get to the bottom of this problem.

**Comment by psiinon** [comment]
For info its looking like its actually this regex that is killing performance: https://github.com/zaproxy/zap-extensions/blob/master/src/org/zaproxy/zap/extension/ascanrules/TestPathTraversal.java#L139
We're seeing a lot of locking and very high processor use.
I hacked a much simpler regex in (which obviously wont find all the right things) and it went from taking 11+ mins to scan Bodgeit with this rule to under 1 min.
Note that the previous version of the rule didnt use the regex.

**Comment by kingthorin** [comment]
Perhaps instead of OR'ing things just doing to two checks independently might be faster?
Actually it seems like half the pattern is meant for Win stuff and half for *nix stuff, so if the correct pattern is checked for the correct inputs things should....maybe.....get happier.

I'll dig into it a bit more.

**Comment by yhawke** [comment]
Ok this was the regex that has been suggested originally for the issue the review came from through a path for the overall implementation. I tried to split it in more regexes originally but then I re-assembled them together because I supposed the computation time should be  better in that way. The bad thng is that in my environment the plugin doesn't take so much time but probably that happened due to the response contents that were smaller probably...

**Comment by yhawke** [comment]
An idea could be to check simply for the occurrence of the combination of the strings for Windows and Linux separately without any regex... because looking at the regex it seems to check only for this...

**Comment by psiinon** [comment]
I think @thc202 is looking into this now. We were thinking it would be better to split the check up to just look for Windows _or_ *Nix depending on the attack. Oh, and hopefully also change the add-on to use the techs ;)

**Comment by yhawke** [comment]
Well, some tests maybe should be performed, but I suppose we can also avoid to use regexes probably, simply checking for the specific presence of the single words for each tech....
