### ISSUE TITLE
[Android] ERR_COMMON_NAME_INVALID error for HTTPS proxy with SNI Terminator

### ISSUE THREAD

**Issue by varunchitre15** [zaproxy/zaproxy#3768]
Hello,

I am trying to get proxy working using iptables on an Android 7.0 device as mentioned here .
https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsSniTerminatorSniTerminator

It appears, I get a NET::ERR_COMMON_NAME_INVALID for any https site I try to access. 
![screenshot jul 20 2017 2-39-43 pm](https://user-images.githubusercontent.com/2326183/28409902-a5be18b0-6d59-11e7-97bd-7894a5d09121.png)

I have already installed the certificate by exporting it from ZAP-->Options-->Dynamic SSL Certificate

On another note: If I set the proxy using Wifi Settings, I don't face this issue. Is there any way to have HTTPS proxy without having to use SNI Terminator and using iptables? Or how can the current issue be fixed?

**Comment by mfruba** [comment]
I have same issue when using android emulator. Burp Suite works fine, when Zap Proxy generates certificates with invalid site name. Tested with Android 5 and 8.

I have configured proxy settings via emulator options Seetings->Proxy->Manual proxy configuration. Usage of "SNI Terminator" does not help.

**Comment by thc202** [comment]
@mfruba are you adding/trusting ZAP's Root CA cert? [1]

[1 ]https://security.secure.force.com/security/tools/webapp/zapandroidsetup

**Comment by mfruba** [comment]
Hi, Yes. I have even imported burp cert to zap (as burp is working without
any issues) with no luck :(

I have seen this guide, but this does not help

11.09.2017 11:57 "thc202" <notifications@github.com> napisał(a):

@mfruba <https://github.com/mfruba> are you adding/trusting ZAP's Root CA
cert? [1]

[1 ]https://security.secure.force.com/security/tools/webapp/zapandroidsetup

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zaproxy/zaproxy/issues/3768#issuecomment-328481492>,
or mute
the thread

**Comment by kingthorin** [comment]
Is it limited to the Android device? Is it working properly from the system on which ZAP is installed? Had you accessed the destinations on the android device before trying to use the proxy? (Couod be a pinning issue, you might need to wipe browser data/cache)

**Comment by mfruba** [comment]
I have tested mitm of https on PC and it works. There is only problem with
android emulator.
No there is no pinning, as I am trying to mitm android application (I have
wiped it's data). I have same issue with web browser on the android
emulator.

11.09.2017 12:36 "kingthorin" <notifications@github.com> napisał(a):

**Comment by kingthorin** [comment]
Well your original example was facebook which definitely uses HSTS and likely also uses HPKP. You used to be able to clear these in Firefox but it seems it no longer allows it (perhaps with an about:config tweak)... Not sure how Chrome behaves, even less so with Chrome on an emulator.

> This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.

**Comment by mfruba** [comment]
I have attempted to mitm this app:
https://play.google.com/store/apps/details?id=ru.mail.calendar
And HSTS/HPKP is not in place, because as I said burp suite proxy works
correctly.

As I said on the beginning zap proxy generates certificates with invalid
server name.

2017-09-11 20:30 GMT+02:00 kingthorin <notifications@github.com>:

**Comment by kingthorin** [comment]
> As I said on the beginning zap proxy generates certificates with invalid server name.

Perhaps you could elaborate on "invalid server name" then. What gets generated? What should get generated (or be matched)? etc. Actual details help, screenshots are good to...

You can tell us A != B, and all we can do is answer "sure good luck with that"... Help us help you!

**Comment by mfruba** [comment]
The following message I receive when using just zap proxy:

![zap_proxy](https://user-images.githubusercontent.com/16609503/30293286-45b2ceb6-9739-11e7-9d52-c7169d4bd721.png)

In case of proxing via "SNI Terminator" it seems that something hangs as, the browser do not receive response.

**Comment by thc202** [comment]
Is ZAP receiving a CONNECT request? (Can be shown with "Show (local) CONNECT requests". [1]) If so which address/domain is it for?

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsView#show-local-connect-requests

**Comment by kingthorin** [comment]
It seems you're chaining your proxies or something, why does it have both ZAP and PortSwigger details?

**Comment by mfruba** [comment]
For local proxy I was able to trigger CONNECT from my pc, but for SNI
Terminator I received null:443 connection:

$ curl -v -k --proxy 192.168.0.10:8443 "https://netflix.com"
* Rebuilt URL to: https://netflix.com/
* Hostname was NOT found in DNS cache
*   Trying 192.168.0.10...
* Connected to 192.168.0.10 (192.168.0.10) port 8443 (#0)
* Establish HTTP proxy tunnel to netflix.com:443
> CONNECT netflix.com:443 HTTP/1.1
> Host: netflix.com:443
> User-Agent: curl/7.35.0
> Proxy-Connection: Keep-Alive
>
<
* Proxy CONNECT aborted
* Connection #0 to host 192.168.0.10 left intact
curl: (56) Proxy CONNECT aborted


-------
It displays burp cert as after multiple attempts I have imported Burp
certificate into Zap. To just make sure that root CA generated by Zap is
fine.

2017-09-11 21:51 GMT+02:00 thc202 <notifications@github.com>:

**Comment by thc202** [comment]
No CONNECT requests from the Android emulator in ZAP?

**Comment by mfruba** [comment]
Result below is mitm from Android emulator.

![zap_proxy](https://user-images.githubusercontent.com/16609503/30296187-93371200-9743-11e7-9879-8abe525a3b57.png)

**Comment by thc202** [comment]
Thanks! Could you provide the whole CONNECT request (as shown in the Request tab) for SNI and Local Proxy?

**Comment by mfruba** [comment]
Not sure if you wanted exactly that, but please check below.

**Local Proxy:**
Req: `CONNECT 98.138.4.253:443 HTTP/1.1`
Resp: `HTTP/1.1 200 Connection established`

**SNI Terminator:**
Req: `CONNECT null:443 HTTP/1.1`
Resp: `HTTP/1.1 200 Connection established`

**Comment by thc202** [comment]
Yeah, that's it. Thanks!

For Local Proxy there's not much that can be done, since we are getting the address instead of the domain name (well, maybe we could try a reverse lookup?).
Regarding the SNI, are you transparently proxying through ZAP? I was not expecting to see the CONNECT request in this case (Android emulator should not be aware of the proxy), but should still try to extract the domain... I'll take a look.

**Comment by mfruba** [comment]
I have used "Seetings->Proxy->Manual proxy configuration" within emulator options (as the emulator iptables does not support DNAT), I have no idea how it works.

**Comment by thc202** [comment]
@mfruba could you try again with latest weekly release? [1] The Local Proxy now supports SNI extension, it might not yet address this case though (but we can check the requested server name after the CONNECT to ensure we return the correct domain instead of the IP address).

[1] https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-weekly

**Comment by kingthorin** [comment]
@mfruba have you been able to try the latest weekly?

**Comment by kingthorin** [comment]
Original reporter hasn't responded after more than 2 weeks, can this be closed?

**Comment by tyzoid** [comment]
Requesting Re-open, this is still an issue. When setting the Emulator proxy to ZAP, it gives certificate errors, because the generated certificate is for the IP address requested (essentially acting as a transparent https proxy). Installing the SNI terminator add-on did not help, and cause requests to drop when the pointing at that proxied port.

![image](https://user-images.githubusercontent.com/974758/55253287-54208700-522b-11e9-9997-383f02900c9e.png)

**Comment by thc202** [comment]
Which ZAP version? SNI Terminator add-on is no longer supported, the local proxies now use/check the SNI.

**Comment by tyzoid** [comment]
This is with ZAP 2.7.0. I see no option for SNI.

![image](https://user-images.githubusercontent.com/974758/55256553-a665a600-5233-11e9-8637-2be280ff02f1.png)
