### ISSUE TITLE
Resend same Fuzzer attack and customize the fuzzer table result 

### ISSUE THREAD

**Issue by giper45** [zaproxy/zaproxy#3875]
I really like ZAP and I'm trying to understand how it works. I'd like to know if these two features are present (because I'm not able to do these things): 

1. When I start a fuzzer, it gives me results after that it finishes. Let's suppose that I choice username and password in fuzzer options, then I send the attack and it fails (I miss right credentials), so I'd like to change the payloads in parameters of the same fuzzer (for example by changing the password and the username list ) and to retry the same fuzzer attack, how can I do this? If I want to retry the same fuzzer I have to create a new fuzzer, reselect the username and password parameters and add the lists again, that is a boring way (especially if I'm testing a lot of parameters) ... how can I automatize this, by sending the same fuzzer attack but by only changing the parameter lists?

2. When I use fuzzer i'd like to set some customized boolean condition in result table (for example in a login attack if I'd like to insert a "false" value if the header response contains the "error " word). Is there a way to customize the headers of the table of fuzzer results with conditions, or with values of a DOM element in http body responses ? 

Thanks in advance!

**Comment by kingthorin** [comment]
Number one isn't currently possible, there's already an open issue for that.

Number two is possible by adding a message processor and tagging script.

**Comment by thc202** [comment]
1. Yes, the issue is #1452.
2. It can also be used the Tag Creator, which shows the tags in the State column. [1]

Closing the issue, all questions seem to be answered. Any other question, please, let us know through the [User Group](https://groups.google.com/group/zaproxy-users). Thank you.

(Feel free to reopen the issue if point 2. is not addressed.)

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsFuzzHttpmessageprocessors#tag-creator
