### ISSUE TITLE
ZAP not saving history, context

### ISSUE THREAD

**Issue by pr0letariat** [zaproxy/zaproxy#3884]
1. Open ZAP
2. Persist session
3. Make a request to an application through the proxy
4. Add the application to a context
5. Close ZAP
6. Open ZAP
7. Open the session from point 2 and observe that the context and history have not been saved

**Comment by thc202** [comment]
ZAP version?

**Comment by pr0letariat** [comment]
2.6.0

**Comment by thc202** [comment]
I'm unable to reproduce the issue with the steps provided. Which option are you using in step 2, "File" > "Persist Session..." ?

Could you check if zap.log has any error? [1]

[1] https://github.com/zaproxy/zaproxy/wiki/FAQconfig

**Comment by pr0letariat** [comment]
`"Yes, I want to persist this session but I want to specify the name and location"`

Unfortunately I can't reproduce the issue now either, despite going through the same steps.

I'll comment again with the zap.log information if it happens again.

**Comment by thc202** [comment]
Closing for now, feel free to reopen it if you have more information. Thank you!

**Comment by giper45** [comment]
Same Problem, but it is difficult to understand when it happens because it doesn't always happen... 
This usually happens with the following steps:

- Open ZAP
- Persist session save name file and location 
- Do some request
- Close ZAP
- Reopen ZAP
- Close the persist session panel with the X button on the top right
- File->Open->saved session 
- Empty session 

I don't know if this happens only when you change the default name to the session (Untitled Session), anyway this is pretty annoying because all the history is lost...

**Comment by njfox** [comment]
I'm experiencing this issue with zaproxy 2.7.0 on Arch Linux. No matter what I do, I cannot get a session to persist if ZAP crashes or is closed--the session is always completely empty when I restart zap and load the session file.

I'm not really sure what additional information I can provide, but let me know if there's something specific I can do to help diagnose.
