### ISSUE TITLE
XSS False Positive: Reflected XSS in PUT Response

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#3979]
Similar to #3978 that I just reported, ZAP is reporting an XSS in the response to a PUT request. For the life of me I can't figure out how an attacker would force a victim to issue a PUT request. Same for other HTTP Methods except GET/POST. As such, I think XSS issues should ONLY be reported for GET/POST requests.

If you aren't sure that only GET/POST are sources for XSS attacks, it might be useful to have a discussion in some forum somewhere to see if anyone can think of a way to launch a successful 'reflected' XSS attack using something other than GET/POST.

**Comment by kingthorin** [comment]
Could you provide the actual request and response?

**Comment by davewichers** [comment]
I can't provide the actual one, but here is a description:

Request: PUT https://somesite/someapp/somepage/ HTTP/1.1
Various headers including: Content-Type: application/json;charset=utf-8
request body is JSON object with six name/value pairs and one of the values is: "<script>alert(1);</script>"

Response: HTTP/1.1. OK
Various headers including: Content-Type: application/json
response body is JSON object with 11 name/value pairs and one of the values is: "<script>alert(1);</script>"

The exact same name/value pair from the PUT request.

Not sure why you want the actual request/response info as I thought the issue description was self explanatory. But if you need more info beyond this, let me know specifically what you are looking for.

**Comment by kingthorin** [comment]
Just needed clarification on how an HTTP PUT was being used to pass params (vs. PUTting a file as it is intended). Now that we know it's API usage of PUT it makes more sense.

We need this level of detail in order to mock-up test cases, etc. or produce rational for whether or not a PUT can be used as a valid XSS vector (as you requested).

There was the whole thing with XST (Cross-site Tracing), granted that's TRACE not PUT. But, it is an example of non-GET/POST XSS. https://deadliestwebattacks.com/2010/05/18/cross-site-tracing-xst-the-misunderstood-vulnerability/

Thanks for the details.

**Comment by thc202** [comment]
Released in version 29 of Active scanner rules add-on.
