### ISSUE TITLE
Passive Scan Tags interpolation

### ISSUE THREAD

**Issue by PenelopeFudd** [zaproxy/zaproxy#4123]
I've created a Passive Scan Tag that matches a request header, and I'd like to use part of the value as a tag.

The Request Header Regex is: "X-Amz-Target: com.amazon.(.*)"
The Configuration is currently: "AmazonAPI"
I'd like it to be: "AmazonAPI $1" or "AmazonAPI \1"

Actually, it'd be awesome if I could recreate AWS command-lines from interpreting the headers.  That's starting to sound like a script, akin to the curl_command_generator.js script!

**Comment by kingthorin** [comment]
@penelopeFudd do you think it would be enough to provide for use of just the first capturing group?

For example:
Assume the following tag regex `(\d{3})` for the following Tag rule:
![image](https://user-images.githubusercontent.com/7570458/38101382-292e0e5c-334e-11e8-9f94-01c9242ab51e.png)

Given 3 inputs:
```
<html>
abc1234
<!-- bleh -->
</html>
```

```
<html>
333
</html>
```

```
<html>
fred
</html>
```

Would produce tags like:
![image](https://user-images.githubusercontent.com/7570458/38101522-8198e1d4-334e-11e8-86a4-a30032658d7a.png)

That might not be as specific as you were thinking when you raise this issue but hopefully it's a good enough illustration.

Capturing group 0 is the whole match, group 1 is the first group in the regex. 
Here's an online example:
http://www.regexplanet.com/share/index.html?share=yyyyyky9par
<sub>Note: You might have to select java then hit test when you visit the link.</sub>
<sub>Note 2: Notice the behavior when you change the pattern to `abc(\d{3})` and hit test.

**Comment by kingthorin** [comment]
@psiinon @thc202 what do you think about implementing just based on group 1 to provide some flexibility?

**Comment by thc202** [comment]
How would that work? If there's a group it's automatically appended to the tag?
(Note that it can be used `Matcher.appendReplacement` to automatically replace the group references in the tag.)

**Comment by thc202** [comment]
Sounds good.

**Comment by kingthorin** [comment]
Here's my initial code: https://github.com/zaproxy/zaproxy/compare/develop...kingthorin:tag-interpolation
It currently only applies to response bodies (but making it applicable to requests and headers isn't a big deal), it could maybe also use some clean up of the var/const names. 

Now that I've done some [reading](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html#appendReplacement(java.lang.StringBuffer,%20java.lang.String)) I'm not sure that `appendReplacement` is applicable here since it's being appended to the tag not the string being searched.

**Comment by thc202** [comment]
The `matcher` could be passed to `matched` and do the group logic there (less changes overall).

> it could maybe also use some clean up of the var/const names.

Which ones?

The use of `appendReplacement` would allow the user to specify where the groups are added/replaced in the tag (instead of being always appended). The input sequence added to the result (`sb`) would have to be ignored but that can be easily done by getting the sub-string with the start of the match.

**Comment by kingthorin** [comment]
Just the stuff I added. PH should actually be PLACEHOLDER, like that.

I’m not following on the appendReplacement thing: The matcher is on the message part (eg response body) not the tag itself.

**Comment by thc202** [comment]
OK.

That's fine/expected, the tag is the `replacement` (which gets the group references replaced in the result).

**Comment by kingthorin** [comment]
I’ll have to try it ;)

**Comment by kingthorin** [comment]
I'm still not seeing it. All I end up with is whatever `getConf()` returns.

Are you picturing some change where the tag itself is also defined by a regex?

**Comment by thc202** [comment]
Not a regex, but use of group references (like in the example provided earlier, `AmazonAPI $1`).

**Comment by kingthorin** [comment]
Bingo, ok that works :+1:
