### ISSUE TITLE
Pretty-printing JSON body view

### ISSUE THREAD

**Issue by PenelopeFudd** [zaproxy/zaproxy#4124]
It's great that JSON responses are auto-detected and syntax highlighted.  I wish it could be taken one step further and pretty-printed with newlines and indentation; the output of 'jq .' would be suitable.

**Comment by kingthorin** [comment]
I believe this is covered by this pull request https://github.com/zaproxy/zap-extensions/pull/1113

**Comment by juhakivekas** [comment]
yes, this is ready and i'm using it in my personal testing. However, currently this causes large messages to do a lot of processing (especially js.map files, since they are huge json objects). 

The PR isn't merged yet, so currently you need to pull my branch and build it. If you do that or this gets merged, then I'm happy to hear improvement suggestions.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1113.

**Comment by thc202** [comment]
The add-on, Json view, is now available in the marketplace.

**Comment by juhakivekas** [comment]
Yay!
