### ISSUE TITLE
owasp/zap2docker-stable http://zap API Endpoint Doesn't Exist

### ISSUE THREAD

**Issue by thiscantbetaken** [zaproxy/zaproxy#4229]
Trying to get around this Swing menuing issue by using the ZAP API. owasp/zap2docker-stable API endpoint at http://zap is not found after configuring the proxy to use localhost:8080:

```
HTTP ERROR 404
Problem accessing /zap. Reason:

    Not Found
Powered by Jetty://
```

**Comment by thc202** [comment]
Could you provide more details on how and from where are you accessing the ZAP API? (Also, the docker command used to start ZAP.)

**Comment by GregoryPerry706** [comment]
Just by pointing the browser at the http://zap endpoint through the proxy itself. This works fine with the standalone Java version, but fails with Docker.

$ docker run -u zap -p 8080:8080 -p 8090:8090 -i owasp/zap2docker-stable zap-webswing.sh

**Comment by thc202** [comment]
OK, it seems that the browser is proxying through 8080 instead of 8090? ZAP is listening on the latter port. But to avoid proxying any Webswing data through ZAP I'd suggest not proxying and accessing the ZAP API with its address (e.g. `http://172.17.0.2:8090` instead of `http://zap/`).

Since you are accessing the API through the host you need to give it access to the API, that's not working through the Webswing UI (per the other issue) so it needs to be specified in the Webswing configuration file (note the `args` property), for example, file under `/path/to/webswing.config` with:
```
{
  "applications" : [ {
    "name" : "ZAP",
    "icon" : "icon.png",
    "mainClass" : "org.zaproxy.zap.ZAP",
    "classPathEntries" : [ "zap-*.jar", "lib/*.jar", "lang/" ],
    "vmArgs" : "",
    "args" : "-host 0.0.0.0 -port 8090 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.disablekey=true",
    "homeDir" : "/zap/",
    "maxClients" : 1,
    "antiAliasText" : true,
    "swingSessionTimeout" : 300,
    "authorization" : false,
    "isolatedFs" : false,
    "debug" : true,
    "authentication" : false,
    "directdraw" : false,
    "allowDelete" : false,
    "allowDownload" : false,
    "allowUpload" : false,
    "allowJsLink" : true
  } ],
  "applets" : []
}
```
and then specify that file when running Docker:
```
docker run -u zap -v /path/to/webswing.config:/zap/webswing-2.3/webswing.config -p 8080:8080 -p 8090:8090 -i owasp/zap2docker-weekly zap-webswing.sh
```

Some references:
https://github.com/zaproxy/zaproxy/wiki/Docker
https://github.com/zaproxy/zaproxy/wiki/FAQapikey

**Comment by thc202** [comment]
Closing, the weekly Docker image is already using a newer version of Webswing (#3553) which fixes the issue that prevented the configuration of allowed addresses through the UI.
