### ISSUE TITLE
Allow to show Request and Response in the same tab

### ISSUE THREAD

**Issue by sbzo** [zaproxy/zaproxy#4331]
Hi, 

I think would be great if requester and request tab could share the same response tab. For laptops with a small screen, I have to change from normal layout to full layout when I'm working with the requester.

Best regards,

RLobo

**Comment by juhakivekas** [comment]
I see this has an add-on tag, but as this issue also affects a few other views (eg. the script console) it might be a good idea to also look at this from a different angle.

Instead of splitting the main panel into two panels for which the other always shows the response tab, what if instead the non-split Request and Response tabs would be combined into one “Response&Request” tab. This way the main tabs would be for example “quick start”, ”scripts”, “request&response”, “resender”. This would fix the issue of the response tab always occupying one side of the split panel.

**Comment by kingthorin** [comment]
I'd labelled it "add-on" because `Requester` was mentioned specifically and is an addon.

Whoever decides to tackle the issue can feel free to change the labels, not a major deal to me.

**Comment by thc202** [comment]
@sbzo could you provide more details on the use case/workflow?

**Comment by juhakivekas** [comment]
@kingthorin I just wanted to suggest that this could be fixed in the core :)

Here's some "pictures" about my proposed solution. The default tabbed view:
```
Work panel:
  Tabs:
    Quickstart
    Request
    Response
    Resender
```
The current side-by-side view:
```
Work panel:
  Tabs:
    Quickstart
    Request
    Resender
  Tabs:
    Response (always occupies space)
```
A more useable side-by-side view:
```
Work panel:
  Tabs:
    Quickstart
    Request&Response:
      Request
      Response
    Resender
```

This approach would give more space in other situations too (scripting) and also fix some resizing issues #3961

**Comment by kingthorin** [comment]
@juhakivekas great, collaboration is wonderful! No such thing as a bad idea :zap: I was just trying to fill in any gap as to why I'd labelled it that way etc. I'm all for a different or more holistic solution.

**Comment by sbzo** [comment]
Excellent approach @juhakivekas, this solution looks acceptable and keep all cleaner.

Hope to see it in soon implementations of ZAP :) 

Thanks, @kingthorin for the follow-up.

**Comment by psiinon** [comment]
We already have some options for reconfiguring the UI, so I think it makes sense for us to have more if thats what people want.
Probably not something that I'd work on, but v happy for anyone else to look at it.
