### ISSUE TITLE
Persist column configuration in History tab

### ISSUE THREAD

**Issue by fd0** [zaproxy/zaproxy#4788]
First: Thank you very much for your work on ZAP!

**Describe the bug**

The HTTP request history tab has several columns. Although by default most columns are shown, users can configure which columns are displayed and in which order. This  information is lost when ZAP is quit, so users have to do this configuration every time.

**To Reproduce**
1. Start ZAP
1. Click on the History tab
1. Configure the columns by clicking in the header row on the rightmost icon
1. Disable the "Id" column, it isn't shown any more
1. Move the Request column to the front
1. Quit ZAP
1. Start ZAP again
1. "Id" column is shown again, Method column is third column, all configuration for the columns was reset

**Expected behavior**

Column configuration for History tab should be the same after restart.

**Software versions**
 - ZAP: 2.7.0
 - OS: Debian stable 9.4 ("stretch")
 - Java: openjdk 1.9, Debian version number: `9~b181-4~bpo9+1`, package `openjdk-9-jre`

**Comment by dafenix** [comment]
hello,

can i take this issue?

**Comment by thc202** [comment]
Sure, do you know where to start?

**Comment by dafenix** [comment]
I thought the `exit` method in `Control.java` would be a good choice for saving the column configuration but i don't know at the moment how i can access the `logPanel` to grab the column settings. Have you any suggestions for me? Maybe there is a more suitable place?

**Comment by thc202** [comment]
This could be added to `ZapTable` (so other tabs/places can benefit from it), where the column changes (added, removed, moved) can be tracked (e.g. `TableColumnModelListener`) and set to the main configuration file (`Model.getSingleton().getOptionsParam().getConfig()`), which is already being saved/persisted when ZAP is shutdown. I'd expect the users of the class to opt-in by setting an ID used as configuration key/prefix for its properties.

Otherwise, you can persist the table's state in `ExtensionHistory.destroy()`.

P.S. You should have a collaboration invite so that we can assign the issue to you.

**Comment by dafenix** [comment]
Ok that's enough to start. Thank you for your advice.

**Comment by thc202** [comment]
No problem, any question just let us know.

**Comment by dafenix** [comment]
#5085 ready for review

**Comment by fd0** [comment]
Wohoo!

**Comment by sbzo** [comment]
Hi team, when this improvement will be released?. 

Best regards.
