### ISSUE TITLE
Requester - Allow to disable cookies

### ISSUE THREAD

**Issue by sbzo** [zaproxy/zaproxy#4934]
**Describe the bug**
Requester tab is not sending changes related to cookies values, the original cookie is always sent and not include the change.

**To Reproduce**
1. Send a request to the requester who had some cookie values.
2. Send the request as is with requester, the original request.
3. Now, change a value in the cookie and send the request. 
4. View in the history tab that the cookie changes are not reflected in the request sent.

Only works if is the first message I send, the next messages force the same cookie. 

**Expected behavior**
All changes made in the request should keep as is at the moment is send.

**Software versions**
 - ZAP: D-2018-08-14 and previous.
 - Add-on: Requester Alpha 2.0.0
 - OS: OS X

![2018-08-16 11 36 53](https://user-images.githubusercontent.com/28350322/44222015-dea6f100-a148-11e8-9146-e00b79ba84a0.gif)

**Comment by kingthorin** [comment]
@sbzo if you select the request from History or Sites Tree then "Open/Resend with Request Editor..." (from the right click context menu) does it behave as expected? [That's the internal editor instead of the Requester addon)

I just checked out the w2018-08-14 build, installed the Requester addon and am unable to recreate the behavior you're describing.

**Comment by sbzo** [comment]
Hi @kingthorin,

I don't know why happened this in the first place, but in the new version, everything works well. Let's continue and close the issue.

Best regards and thanks for the review.

**Comment by thc202** [comment]
This can be reproduced if a/the cookie is set when sending the message through the Requester tab, when sending the request in tab 12 you can see the Set-Cookie header. This also happens with the built-in editor though ,#1164, because the editors have the cookies enabled by default.

Reopening so that we don't forget the Requester add-on.

**Comment by sbzo** [comment]
@thc202 thanks for explain to us, I felt confuse 😅😅 why happens that time and now doesn't work.

to reproduce this behavior have to met few conditions, I never image that.

RLobo

**Comment by thc202** [comment]
Released in version 4 of Requester add-on.
