### ISSUE TITLE
A way to reduce untitled1.data file size

### ISSUE THREAD

**Issue by Xetzer** [zaproxy/zaproxy#5101]
Hello, I have a problem with `untitled1.data` file size.
I'm trying to run ZAP active scan using zap-cli:
```
zap-cli --zap-path /opt/software/ZAP_2.7.0/ -p 8090 start -o '-config api.disablekey=true' >> zap.log
zap-cli quick-scan -s all --spider -r https://example.com -l Informational >> zap.log
```
During the scan a size of session database file `~/.ZAP/session/untitled1.data` increases to 17 GB, thus consuming all the free space on the HDD. Unfortunately, in my case there is no possibility to simply extend disk size.
I've tried to reduce the number of scanners (e.g. running quick-scan with `-s xss` option), but it didn't have any positive effect.
Is there a way to reduce a size of database file or somehow restrict it?

**Comment by kingthorin** [comment]
Are you re-using the same session all the time?

**Comment by Xetzer** [comment]
@kingthorin, scans are launched from Docker containers, so every new scan begins from scratch.

**Comment by kingthorin** [comment]
We’ll you could specify an output path and persist the session at least temporarily instead of using a non-persisted session that’s being written to user profile space?

(Well at least I assume you can, zap-cli is third party.)

Or you could actually drive ZAP via it’s API instead of using a wrapper/abstraction.

Or you could somehow reduce your scope (target) or scan policy.

**Comment by kingthorin** [comment]
No further input from the original submitter in more than 4 months. Closing.
