### ISSUE TITLE
Reflected XSS False Positive?

### ISSUE THREAD

**Issue by lesar** [zaproxy/zaproxy#5479]
I'm testing and zap give me this alert:  
`Cross Site Scripting (riflesso)`  

and in the response html I found:  
`<input type="hidden" id="currSelName" name="currSelName" value=" onMouseOver=alert(1);"  />`  

but this javascript is not in an executable zone: it is inside a string and cannot be execute.  

put this in the page is easy: in the querystring one can write  
currSelName=" onMouseOver=alert(1);"  

This is not a problem or dangerous. Why zap make an alert?  
It is a zap error or my mistake?  
How can disable this false positive?  

Best regards,  
Leonardo

**Comment by kingthorin** [comment]
> This is not a problem or dangerous. Why zap make an alert?

Because making a FP free scanner is essentially impossible.
Based on the description here it could easily be turned into a functional XSS.

> It is a zap error or my mistake?

Not enough detail to know.

> How can disable this false positive?

Double click the alert, select "False Positive" in the 'Risk' dropdown, click 'Save'. (Or use Context Alert Filters, or modify it though the web API).

**Comment by lesar** [comment]
Tanks.  
What do you mean writing:. 
"Based on the description here it could easily be turned into a functional XSS."?

Best regards

**Comment by psiinon** [comment]
He means that based on the information you've provided it looks distinctly possible that while the example given in the alert wouldnt run its entirely possible that a slightly different attack would run on the target page.
The ZAP XSS scanner tries to break out of the HTML context that the payload is reflected in. If it appears to be possible then ZAP raises an alert - that doesnt mean the example given will actually work, but its likely that a slightly different one will.
You need to manually tes that to see if its possible or not. We dont have access to you application so cannot tell how it will react.
If you are sure its a false positive then please provide more details so that we can try to fix the rule. A simple PoC would be ideal :)

**Comment by lesar** [comment]
Ok thanks.  
I'm using java and [freemerker ver. 2.3.19](https://freemarker.apache.org/) that is not the last version and I cannot change it.  

The criminal output field is:  
`<input type="hidden" id="currSelName" name="currSelName" value=" onMouseOver=alert(1);" />`  

the code that make above output is:  
`<input type="hidden" id="currSelName" name="currSelName" value="${currSelName!?js_string?html}"  />
`  

[?js_string](https://freemarker.apache.org/docs/ref_builtins_string.html#ref_builtin_js_string) and [?html](https://freemarker.apache.org/docs/ref_builtins_string.html#ref_builtin_html) filter the output and `?html` is deprecated now but wasn't in 2.3.19 version  
(new version use new filter mode)  

So I think that this is a False positive Reflected XSS.  

you agree or is my mistake?  

best regards,
Leonardo

**Comment by kingthorin** [comment]
Try an injection that will cause a valid XSS. Close the value quote, change to onLoad or some other event (obviously you can't mouseOver a hidden field). Or try using the fuzzer with an XSS payload list instead of just using active scan. It seems like there is limited or no filtering/protection.

Consider contracting an actual Security Tester or Penetration Tester.

**Comment by lesar** [comment]
Ok, thanks very mutch.  I Will try.

**Comment by fraenku** [comment]
I am using the Java Encoder Project (https://www.owasp.org/index.php/OWASP_Java_Encoder_Project), this library applies minimal encoding, therefore the following examples will not be encoded:

<input type="hidden" id="currSelName" name="currSelName" value=" **onMouseOver=alert(1);**" />
or
**<td>;alert(1)</td>**

ZAP however marks them as valid injections, which is false.

**Comment by psiinon** [comment]
We should look at improving the code so that ZAP handles these sort of cases - its all a questions of how we parse the HTML context.

**Comment by kingthorin** [comment]
I’m closing this one, that the field happens to current Loy be hidden does not remove the issue, if our test was onkeypress or some other event it would still actually trigger.
