### ISSUE TITLE
[META] Closing Issues for Old Releases

### ISSUE THREAD

**Issue by kurobeats** [zaproxy/zaproxy#5483]
I propose that the project closes issues related to previous ZAP releases to get the number of issues down to a manageable and (developer) inviting level. At it's present number (641 at this time), its quite daunting.

Similar to bugzilla reports regarding EOL Fedora bugs, here's a mock-up of a message that could be included with issue closures:

```
This message is a notification that the version of ZAP proxy which this bug 
is in relation to has reached its end of life. It is ZAP proxy's policy to 
close all bug reports from releases that are no longer maintained.

Thank you for reporting this issue and we are sorry that we were not 
able to fix it before the afected version of ZAP proxy reached its end 
of life. If you would still like to see this bug fixed and are able to 
reproduce it against a current version of ZAP proxy, you are encouraged 
change the 'version' to a later ZAP proxy version.

Although we aim to fix as many bugs as possible during every release's
lifetime, sometimes those efforts are overtaken by events. Often a
more recent ZAP proxy release includes newer upstream software that fixes
bugs or makes them obsolete.
```

**Comment by psiinon** [comment]
I like it!

**Comment by kingthorin** [comment]
I'm not sure simply closing issues is a good tactic here.

Are devs daunted by knowing there are things to work on? (That seems backward to me.)
If 640'ish is discouraging then why does anyone ever work on Gradle or MySQL? 

- Gradle has 1740 as I type this... https://github.com/gradle/gradle/issues/
- MySQL has almost ~5,700 open bugs.... https://bugs.mysql.com/bugstats.php

Nearly half of the open issues are for enhancements which don't cease to be enhancement requests just because we've done a new release.

On top of that many of the older issues are still valid and carried from the GoogleCode migration, so we can't reach back out to the original submitters.

I do regularly review the issue tracker (2 to 4 times a year) and prune the chaff or try to spark further input on tickets that are lacking detail, etc.

**Comment by kurobeats** [comment]
All good points raised @kingthorin. Ultimately, its the dev team's call to make, this was just a suggestion.

**Comment by thc202** [comment]
Closing, suggestion received, we'll discuss it.
