### ISSUE TITLE
Unit tests for HeartBleedScanner

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#5494]
Create unit tests for [HeartBleedScanner](https://github.com/zaproxy/zap-extensions/blob/master/addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/HeartBleedScanner.java).

Unit tests should test all of the associated functionality and include tests for false positives.
The tests should at least check the number of alerts and the parameters and evidence (as appropriate). Additional checks can be made if thought useful.
Tests for other rules can be found in https://github.com/zaproxy/zap-extensions/tree/master/addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules

**Comment by psiinon** [comment]
This issue is part of the ZAP Unit Test Bounty: https://www.bountysource.com/issues/77734383-unit-tests-for-heartbleedscanner
Bounties will be paid only when the PR has been merged. The PRs must test all of the associated rule functionality and must conform to our Development Rules and Guidelines: https://github.com/zaproxy/zaproxy/wiki/DevGuidelines#unit-test-specific-guidelines
