### ISSUE TITLE
Unit tests for Base64Disclosure

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#5497]
Create unit tests for [Base64Disclosure](https://github.com/zaproxy/zap-extensions/blob/master/addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java).

Unit tests should test all of the associated functionality and include tests for false positives.
The tests should at least check the number of alerts and the parameters and evidence (as appropriate). Additional checks can be made if thought useful.
Tests for other rules can be found in https://github.com/zaproxy/zap-extensions/tree/master/addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules

**Comment by psiinon** [comment]
This issue is part of the ZAP Unit Test Bounty: https://www.bountysource.com/issues/77734380-unit-tests-for-base64disclosure
Bounties will be paid only when the PR has been merged. The PRs must test all of the associated rule functionality and must conform to our Development Rules and Guidelines: https://github.com/zaproxy/zaproxy/wiki/DevGuidelines#unit-test-specific-guidelines

**Comment by psiinon** [comment]
@cotonne are you going to claim the bounty? Its yours for the taking :) If not we'll claim it and donate it back to OWASP...

**Comment by cotonne** [comment]
Yes, you can donate it back to OWASP as a personal contribution from me ;)

Le jeu. 10 mars 2022 à 15:29, Simon Bennetts ***@***.***> a
écrit :

**Comment by psiinon** [comment]
Many thanks!
