### ISSUE TITLE
Unit tests for InsecureComponentScanner

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#5498]
Create unit tests for [InsecureComponentScanner](https://github.com/zaproxy/zap-extensions/blob/master/addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/InsecureComponentScanner.java).

Unit tests should test all of the associated functionality and include tests for false positives.
The tests should at least check the number of alerts and the parameters and evidence (as appropriate). Additional checks can be made if thought useful.
Tests for other rules can be found in https://github.com/zaproxy/zap-extensions/tree/master/addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules

**Comment by psiinon** [comment]
This issue is part of the ZAP Unit Test Bounty: https://www.bountysource.com/issues/77734379-unit-tests-for-insecurecomponentscanner
Bounties will be paid only when the PR has been merged. The PRs must test all of the associated rule functionality and must conform to our Development Rules and Guidelines: https://github.com/zaproxy/zaproxy/wiki/DevGuidelines#unit-test-specific-guidelines

**Comment by bunysae** [comment]
The InsecureComponentScanner-class depends on the VulnerabilityCache-Database (SQLite-Database).
Before starting the test my approach would be creating a fresh vulnerability-cache in the setup of the unit-test. But i can't really figure out the database-scheme. Is the creation of the database-scheme located inside the [zap-extension-repository](https://github.com/zaproxy/zap-extensions), so that i can reuse it in the unit-test or where is the database-scheme created?

**Comment by thc202** [comment]
The test should not need to use a database, the scanner `InsecureComponentScanner` should be changed to allow to set a `VulnerabilityCache`, which should be mocked to return the required `CVE`s.

**Comment by thc202** [comment]
@bunysae you should be able to claim the bounty.
