### ISSUE TITLE
Throws exit code 2 on Jenkins Pipeline

### ISSUE THREAD

**Issue by s1405** [zaproxy/zaproxy#5507]
A shell script is included in a Jenkins job to execute the following commands:
chmod +x /zap/zap-baseline.py
/zap/zap-baseline.py -t https://example.com

It shows normal output until the last line which is
FAIL-NEW: 0	FAIL-INPROG: 0	WARN-NEW: 4	WARN-INPROG: 0	INFO: 0	IGNORE: 0	PASS: 10

However the build fails with the following output at the end of the console output of the Jenkins job
ERROR: script returned exit code 2
Finished: FAILURE

**Comment by psiinon** [comment]
Yep, thats how its supposed to work.
https://github.com/zaproxy/zaproxy/blob/develop/docker/zap-baseline.py#L31-L36

**Comment by s1405** [comment]
is there an example for the -u option, the parameters we need to specify inside the config file

**Comment by thc202** [comment]
The following wiki page explains what's expected in the config file: https://github.com/zaproxy/zaproxy/wiki/ZAP-Baseline-Scan#configuration-file

**Comment by s1405** [comment]
a lil confused I ve seen that earlier and I think that talks about the -g option?, I am jus tryn to see if I can customize the exit code behaviour based on the number of fails or warnings, https://github.com/zaproxy/zaproxy/blob/develop/docker/zap-baseline.py#L31-L36

**Comment by psiinon** [comment]
The ZAP User Group is a better place to discuss these things rather than on a closed issue :)
https://groups.google.com/group/zaproxy-users

**Comment by thc202** [comment]
(For the record.)

Right, that mentions `-g` as it allows to generate a default configuration file (if you don't want to write one from scratch). The resulting configuration file (after tweaks if needed) would be used with `-c`.

Not directly, only by changing the levels in the configuration file you can control the number of WARNs/FAILs and thus the exit code. You can ignore WARNs with `-I` though (so that it exits with non-zero code only when there's a FAIL).
