### ISSUE TITLE
Enhancement: Export Report - PDF Output

### ISSUE THREAD

**Issue by gordonbmu** [zaproxy/zaproxy#5535]
I am using ZAP 2.8.0. When I try to export a report, I am met with the error message, "Notice: PDF is currently unavailable, expected release is v2.0". Can this please be looked into and fixed?

![Capture](https://user-images.githubusercontent.com/54360229/63431133-31feef80-c3ec-11e9-8c79-846a8e7886ea.PNG)

**Comment by kingthorin** [comment]
It's not "throwing" an error, it's an informational dialog.

Unfortunately the Export Report addon was provided by a community member who is no longer active. If someone feels like tackling this please let us know.

**Comment by JFM9** [comment]
The export to PDF functionality has previously been implemented in the `alertReport` extension.

I will be working on merging the `alertReport`'s PDF functionality into `ExportReport`.

**Comment by JFM9** [comment]
While looking into merging `alertReport` into `ExportReport`, I noticed there are currently 3 extensions which appear to have similar functionality:

- alertReport: exports in PDF, ODT
- customreport/Report Extension: exports in HTML, XML, JSON, Markdown
- exportreport: exports in xHTML, XML, JSON

**Comment by thc202** [comment]
Yes, the report add-ons (also `birtreports`) were added along the years each one providing (slightly) different customisation (e.g. filter by alerts, risk, details) or formats.
(It's better to refer to the whole as "add-on" instead of "extension", the latter is more specific implementation detail).

The `customreport` add-on provides only HTML format. We also have core providing reports, in HTML, XML, JSON, and markdown.

As mentioned in IRC (IMO) we should merge those add-ons, although that was not yet decided.
