### ISSUE TITLE
Drheader integration

### ISSUE THREAD

**Issue by javixeneize** [zaproxy/zaproxy#5687]
Hi

We have developed a tool that analyses the security headers in a response against a set of rules in a yaml file. 

We would like to integrate this with ZAP, but i am not sure what is the best approach. Should we write it as a external plugin, or would you recommend to add a feature to our tool that consumes ZAP API and feeds the headers captured to our tool to be analysed?

Thanks :)

**Comment by shooking** [comment]
Could the ZEST or JS scripting work here?
That is trigger your check based on header script rule?

**Comment by javixeneize** [comment]
It is one of the options. The other one is writing a python module that uses the zap library to consume the api.
Or maybe we can do both? ;)

**Comment by kingthorin** [comment]
- You could setup the necessary details to launch drheader from within Zap (while passing details from within Zap). (https://sathisharthars.com/2015/04/15/intergrating-pentesting-applications-in-owsap-zap/)
  - https://github.com/zaproxy/zaproxy/issues/1579
  - https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsInvokeConcepts
  - https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsInvokeOptions
- You could turn it into a library that could be leveraged by Zap's Jython addon.
- You could build it as a zap addon, passive scan rule, script (or scripts) instead of doing something totally separate.

**Comment by javixeneize** [comment]
Thanks for the info! We will keep you posted with progress
