### ISSUE TITLE
Fuzzer runs progressively slower

### ISSUE THREAD

**Issue by jmhickman** [zaproxy/zaproxy#5701]
**Describe the bug**
When using the Fuzzer to brute force a string in a request (such as a password) while making use of the timing throttle, the requests get slower and slower over time.

**To Reproduce**
1. Set up a fuzz on a string in a request. Payload is usually a list of strings, but it doesn't matter.
2. Use the timing and throttling controls to set 1-5 threads, and a timing of 250ms.
3. Start the fuzzer.
4. The attack will start off fast but very quickly drop off in speed, far far beyond the manual timing set in the control.

**Expected behavior**
The timing between requests should stay constant at the setting provided by the user.

**Software versions**
ZAP 2.8.1
OS: Linux 64bit
OpenJDK 1.8.0_232
Firefox 70

**Additional context**
The timings get progressively worse (despite the site itself responding in a relatively constant speed) which makes me think that whatever is computing the timing per thread is periodically increasing the indicated timing (250ms) in additive fashion.

**Comment by thc202** [comment]
After how many requests are you seeing that behaviour?

**Comment by jmhickman** [comment]
I see it almost immediately. It seems to rachet every 10 requests or so per thread, so more threads takes longer between rachets.

**Comment by iwesselk** [comment]
I have noticed the same behavior.
**To Reproduce**
1. Set up a fuzz on a string in a request. Payload set to a list of numbers 1-100
2. Use the timing and throttling controls to set 1-5 threads, and a timing of 250ms.
3. Start the fuzzer.
4. The attack will start off fast but very quickly drop off in speed, far far beyond the manual timing set in the control.
This was not induced by the server side, with low RTT trips of 1-4ms. The server I tested on was a local host python flask hello world example.

**Expected behavior**
The timing between requests should stay constant at the setting provided by the user.

Software versions:
Zap 2.9.0
Windows 10
Java AdoptJDK 11.06

**Comment by iwesselk** [comment]
I have noticed the same behavior.
**To Reproduce**
1. Set up a fuzz on a string in a request. Payload set to a list of numbers 1-100
2. Use the timing and throttling controls to set 1-5 threads, and a timing of 250ms.
3. Start the fuzzer.
4. The attack will start off fast but very quickly drop off in speed, far far beyond the manual timing set in the control.
This was not induced by the server side, with low RTT trips of 1-4ms. The server I tested on was a local host python flask hello world example.

**Expected behavior**
The timing between requests should stay constant at the setting provided by the user.

Software versions:
Zap 2.9.0
Windows 10
Java AdoptJDK 11.06

**Comment by TravisDecker** [comment]
Following steps provided by @jmhickman and @iwesselk, I was unable to reproduce the issue. 
I ran the attack against a spring web application running on Local Host and noticed no slow down. 

Software versions:
Zap 2.9.0
macOS Mojave - 10.14.6
Java OpenJDK 10.0.2

**Comment by wadim-al** [comment]
With 1 second interval and 1 thread I can reproduce this on real sites after 10 requests. At 64th request the pause is 15 seconds. I was fuzzing the URL path. Please see the video. RTT is 160-180. No outgoing proxy used.

https://youtu.be/ifeWC3I333g

Make sure to test with 1 sec interval, 1 thread and a real site with RTT higher than 150.
Turn on the "follow redirects" feature.

This easy to reproduce issue forces me to write my own fuzzer. This issue was present since 2.7.0

**Software versions**
ZAP: D-2020-06-08
OS: Windows 10 x64 2004
Java: Oracle JRE 1.8.0_251 32|64

If any additional evidence is needed, please ask.

**Comment by jmhickman** [comment]
Still waiting on this to be addressed. Conducting assessments using an application with a broken throttle is unacceptable; no real-world client is okay with a tester blitzing their application with 0 throttle for hundreds or thousands or tens of thousands of requests.

**Comment by kingthorin** [comment]
Yes, we know this is still not addressed. The issue is still open 🤪 

Zap is not a commercial product. It's Open Source and produced/maintained by volunteers. Things are fixed as and when possible based purely on interests of the individuals. As you can see there are quite a number of issues that need to be addressed.

The project is always open to new contributors.

**Comment by wadim-al** [comment]
@kingthorin is there any way to upvote this? Is there any way to mark this as major feature breaker?

**Comment by jmhickman** [comment]
Yes, I'm quite aware of how open source works. I'm doing my part as a non-Java programmer to remind the developers that core functionality is broken, has been broken for almost a year (plus however long it was broken before I raised the issue), and hasn't been addressed despite hundreds of commits and many pre-release versions.

Did _you_ remember this issue was still open before I posted? Or perhaps did I remind you?

I just wanted the thing fixed. If I could do it myself I would have a long time ago.

**Comment by kingthorin** [comment]
> @kingthorin is there any way to upvote this? Is there any way to mark this as major feature breaker?

You could setup a bounty via bounty source I guess. https://www.bountysource.com/teams/zap/issues Or you can give it a thumbs up though I'm not aware of anyone prioritizing things that way.

> Did you remember this issue was still open before I posted? Or perhaps did I remind you?

Did I remember this specific issue existed? No. Do I remember daily that there are 100s of open issues? Yup. Yet I'm still a volunteer and work on what interests me, not necessarily things that people get uppity about.

**Comment by jmhickman** [comment]
Are you implying that those 100's of daily new issues are all of similar importance to broken core functionality?

**Comment by kingthorin** [comment]
No I’m implying that there are 100s of issues to tackle overall, some of which have existed for much longer than this and impact everything from typos to core functionality.

None of the volunteers are told what to work on. And no bit of functionality or user is entitled to attention. While you may feel this is huge there are 10s of thousands of other daily users for which this isn’t an issue at all.

Anyway you’ve shared your reminder, thanks for stopping by. It’ll be fixed when it’s fixed.

**Comment by wadim-al** [comment]
@kingthorin 
I can see executor.setIncrementalDefaultDelay(true); in line 196 at fuzz\src\main\java\org\zaproxy\zap\extension\fuzz\AbstractFuzzer.java

May it be it?

**Comment by thc202** [comment]
Although it's related that's not the issue.
