### ISSUE TITLE
FEATURE: Ability to import the exported list of Installed Marketplace Add-ons

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#5853]
It's currently possible in the Marketplace to click on the top of the scroll bar to export the currently installed plugins from the Marketplace.
This makes a very handy CSV file with a nice list of installed plugins.
Now, the developers would like to use the exact same plugins in order to reproduce the results from our scan. 
Currently, this means typing each plug in one for one into the search bar or scrolling and clicking the checkboxes. 
Importing the exported CSV so that the same plugins can be shared and used from the IT Sec ZAP instance to the Developers ZAP instances, would be very helpful.

![2020-02-10_ExportMarketplaceAdd-ons](https://user-images.githubusercontent.com/10052587/74170809-c58fdb00-4c2d-11ea-873b-9b4a67269856.png)

The Import menu and Options menus don't seem to contain this functionality.
![2020-02-10ImportMenuNoImportPlugins](https://user-images.githubusercontent.com/10052587/74170810-c6c10800-4c2d-11ea-8294-3e08e79ad523.png)

**Comment by kingthorin** [comment]
As you've already noted the list can be easily Exported.
You can also highlight the table and copy then paste elsewhere.

Importing add-ons from this info isn't really practical. Add-ons can be install or updated from the CLI and API. So you could easily create a wrapper that consumes the CSV, though it isn't terribly practical because the marketplace table doesn't contain the actual add-on IDs. However support info (either from the [Help menu](https://www.zaproxy.org/docs/desktop/ui/tlmenu/help/#support-info) or CLI does though).

See:
https://www.zaproxy.org/docs/desktop/cmdline/
- `-addoninstall`
- `-addonupdate`
- `-suppinfo` Lists the installed add-ons (including IDs)

**Comment by thc202** [comment]
Automation Framework might be a better way now, to replicate the required state.
https://www.zaproxy.org/docs/desktop/addons/automation-framework/
