### ISSUE TITLE
Unable to get the report from docker after mounting the pwd

### ISSUE THREAD

**Issue by palok86** [zaproxy/zaproxy#5881]
**Describe the bug**
While running the below command
docker run -v $PWD/report/:/zap/wrk/ owasp/zap2docker-stable zap-full-scan.py -t http://192.168.1.95:8000/bodgeit/ -g gen.conf -r testreport.html
unable to get the testreport.html in my current directory
**To Reproduce**

**Expected behavior**
Should be able to get the report in my current directory
**Screenshots**
![image](https://user-images.githubusercontent.com/18442604/75682150-e947bd80-5ccf-11ea-8a25-58fcf19f1bdb.png)

**Software versions**
 - ZAP: [note that we typically only support the latest version of ZAP]
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://www.zaproxy.org/faq/how-do-i-see-what-version-of-an-add-on-extension-i-have-installed/]
 - OS: [e.g. Windows 10]
 - Java: [e.g. openjdk version "1.8.0_171"]
 - Browser: [e.g. chrome 66, firefox 59, safari 11.1]

**Errors from the zap.log file**
See https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/ for the location of the zap.log file for your OS.

**Additional context**

**Comment by psiinon** [comment]
Just tried this and I got:
`ERROR Permission denied`

Tried again removing the `/report/` ie: `docker run -v $PWD:/zap/wrk/ owasp/zap2docker-stable zap-full-scan.py -t http://192.168.1.95:8000/bodgeit/ -g gen.conf -r testreport.html` and it worked :)

So ... do that :)

**Comment by piyushsonigra** [comment]
I am getting permission denied error when i run owasp/zap2docker-stable on Github actions using ubuntu-18.04 as OS.
I have zap target inside Makefile, below is the command I am running
`
docker run -u zap -v $(PWD):/zap/wrk/:rw owasp/zap2docker-weekly zap-full-scan.py -t https://domain -r report.html -z "-configfile /zap/wrk/zap-options.prop"`

error
`ERROR [Errno 13] Permission denied: '/zap/wrk/report.html'`

------
When i pass option `-u root` instead of `-u zap` in docker command i am getting below error

`Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/zap/ which is owned by zap.)
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/zap/ which is owned by zap.)`
