### ISSUE TITLE
ZAP docker scripts do not take context into account while scanning

### ISSUE THREAD

**Issue by jyothsna** [zaproxy/zaproxy#5897]
**Describe the bug**
Docker zap scripts ,say zap_full_scan.py , don't use context for spider, ajaxspider or active scanning even though the scripts import the context

**To Reproduce**
1. pull zap2docker image stable or weekly ;  docker pull owasp/zap2docker-stable
2.  docker run -t -p 8092:8092  -v "$(pwd):/zap/wrk/"   owasp/zap2docker-stable ./zap-full-scan.py -t "https://appURL.com" -g gen.conf -r testreport.html -n /zap/wrk/app.context

3. Observe the console logs and notice that spider/ajaxspider or active scan API calls to ZAP scanner do not pass context name/id so the context is not loaded.
2020-03-13 05:29:20,228 http://localhost:8092 "GET http://zap/JSON/spider/action/scan/?url=https%3A%2F%2Fappurl.com&apikey= HTTP/1.1" 200 12
Any authentication happening is because of the forced user added .
4. Excluded urls present in context are not honored as the context is not used while spidering/ajaxspidering or scanning.

**Expected behavior**
Using an additional option or using the existing "-n" option the docker python scripts should not only import the context but use it while initiating spidering/ajaxspidering/active scanning.

**Software versions**
 - ZAP: pull zap2docker image stable or weekly ;  

**Additional Context**
For example, if we take a look at active scan hook, it doesn't take Zap context into consideration.
@hook(wrap=True)
def zap_active_scan(zap, target, policy):
    logging.debug('Active Scan ' + target + ' with policy ' + policy)
    ascan_scan_id = **zap.ascan.scan(target, recurse=True, scanpolicyname=policy)**
    time.sleep(5)
    while(int(zap.ascan.status(ascan_scan_id)) < 100):
        logging.debug('Active Scan progress %: ' + zap.ascan.status(ascan_scan_id))
        time.sleep(5)
    logging.debug('Active Scan complete')
    logging.debug(zap.ascan.scan_progress(ascan_scan_id))

**Comment by psiinon** [comment]
Thanks for reporting this. Hopefully this shouldnt be too hard to fix - anyone fancy having a go at it?

**Comment by sshniro** [comment]
Shall I give it a try?

**Comment by beldcode** [comment]
Hello,

I found that the `zap_import_context()` function (_docker/zap_common.py_) is used in the Python script which runs after starting the container (_docker/zap-full-scan.py) to_ load contexts. 

The mentioned function says: `zap.context.import_context(context_file)`. However, the corresponding method which is supposed to be called might be `importContext()` from the `Context`-Class (_php/api/zapv2/src/Zap/Context.php_). If that's true, then `zap.context.import_context(context_file)` (snake case) must be `zap.context.importContext(context_file)`. (camel case)

General question:
Do you put different links (which shall be pentested) in the contexts-file(_https://www.zaproxy.org/docs/desktop/start/features/contexts/_) and pass it to the docker container?

Best regards!

**Comment by thc202** [comment]
There are several ZAP API client implementations, the one used in the scripts is the Python one (https://github.com/zaproxy/zap-api-python). That function call is correct, the context is imported, the issue is that the spiders/ascan are being started without the context.

Not directly, the context just controls if a given URL should be tested or not, it does not provide the ones that should, that would be given by the target (and other discovery methods, spider, API imports).

**Comment by psiinon** [comment]
I think the problem is that while the context is imported: https://github.com/zaproxy/zaproxy/blob/develop/docker/zap-baseline.py#L313 it is not passed to zap_spider: https://github.com/zaproxy/zaproxy/blob/develop/docker/zap-baseline.py#L327
So zap_spider needs a new optional `context` param that it can use at https://github.com/zaproxy/zaproxy/blob/develop/docker/zap_common.py#L375 as per https://www.zaproxy.org/docs/api/#spideractionscan

The ajax spider and active scan calls will need the same change.
