### ISSUE TITLE
CSP Scanner rule uses wrong string in alerts (frame-ancestor)

### ISSUE THREAD

**Issue by jpjokinen** [zaproxy/zaproxy#6014]
**Describe the bug**

The scanner tries to find a CSP directive called 'frame-ancestor'. 

I believe this might be the correct source code:
https://github.com/zaproxy/zap-extensions/blob/eef3cf2611f07a6995b4f5c6413e6ca9476d6c9b/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanner.java
 
But the correct directive is 'frame-ancestors', so it flags sites that use 'frame-ancestors' correctly. 

Sources:
https://www.w3.org/TR/CSP3/#directive-frame-ancestors

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

Running a site with 'frame-ancestors' results to a good score with this checkup tool:
https://csp-evaluator.withgoogle.com/

**To Reproduce**

Run ZAP against any site that has Content-Security-Policy header with the 'frame-ancestors' directive set.

**Expected behavior**
No alert should be raised if the site uses 'frame-ancestors' directive. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5868554/83139609-544d3880-a0f5-11ea-8648-70aaf19c9bf3.png)

![image](https://user-images.githubusercontent.com/5868554/83139531-37186a00-a0f5-11ea-84b2-be67f4cba85d.png)

**Software versions**
```text
Version: 2.9.0
---
Installed Add-ons: [[id=alertFilters, version=10.0.0],
[id=ascanrules, version=34.0.0], [id=bruteforce,
version=9.0.0], [id=diff, version=10.0.0],
[id=directorylistv1, version=4.0.0], [id=fuzz,
version=12.0.0], [id=gettingStarted, version=11.0.0],
[id=help, version=10.0.0], [id=hud, version=0.10.0],
[id=importurls, version=7.0.0], [id=invoke, version=10.0.0],
[id=onlineMenu, version=7.0.0], [id=openapi,
version=15.0.0], [id=pscanrules, version=28.0.0],
[id=quickstart, version=28.0.0], [id=replacer,
version=8.0.0], [id=reveal, version=3.0.0],
[id=saverawmessage, version=5.0.0], [id=savexmlmessage,
version=0.1.0], [id=scripts, version=26.0.0], [id=selenium,
version=15.2.0], [id=spiderAjax, version=23.1.0], [id=tips,
version=7.0.0], [id=webdriverwindows, version=17.0.0],
[id=websocket, version=21.0.0], [id=zest, version=32.0.0]]
---
Operating System: Windows 10
Java Version: Oracle Corporation 11.0.1

```

**Comment by kingthorin** [comment]
Thanks for catching this. I'll get a fix in ASAP and we'll publish a new add-on shortly. There's a bunch of other changes we'd like to get out to people anyway.

**Comment by kingthorin** [comment]
@jpjokinen can you confirm that the CSP specific to https://sanako-connect-internal.herokuapp.com/assets is simply `default-src 'none'`? Also, the screenshot showing the verbose policy is for a different response?

It is our belief that although you did note a typo the details provided are un-related. The alert in the second screenshot is correct because `frame-ancestors` directive doesn't fallback to `default-src`.

https://www.w3.org/TR/CSP/#directive-frame-ancestors

**Comment by kingthorin** [comment]
@jpjokinen can you confirm that the CSP specific to https://sanako-connect-internal.herokuapp.com/assets is simply `default-src 'none'`? Also, the screenshot showing the verbose policy is for a different response?

It is our belief that although you did note a typo the details provided are un-related. The alert in the second screenshot is correct because `frame-ancestors` directive doesn't fallback to `default-src`.

https://www.w3.org/TR/CSP/#directive-frame-ancestors

**Comment by kingthorin** [comment]
Submitted hasn't followed-up in 10 days, assuming our hunch is correct. Closing issue.
