### ISSUE TITLE
How to increace font size in macos 

### ISSUE THREAD

**Issue by kaze-nomamani** [zaproxy/zaproxy#6290]
When I go to preferences -> display, font size(General Font & Work Panels )Font is set to -1 & it is not changeable... 

How macos user can change font size?

**Comment by psiinon** [comment]
For some reason that I cant quite remember font resizing is disabled with the "Mac OS X" Look and Feel.
Change to "Nimbus", restart ZAP and then you will be able to change the font size. Note that this will only take effect after a restart.
In the future please ask questions on the User Grpoup rather than raising an issue: https://groups.google.com/group/zaproxy-users
