### ISSUE TITLE
Site tree doesnt correctly represent URLs ending in a /

### ISSUE THREAD

**Issue by whng8** [zaproxy/zaproxy#6297]
**Describe the bug**
In the History tab I added a breakpoint for a particular URL. In the Add Breakpoint window, the prefilled String does not match the URL.

**To Reproduce**
1. Run Python's HTTP server via "python3 -m http.server"
2. In Firefox browse to http://127.0.0.1:8000/search/?q=test (The page will give a 404 error, but that doesn't matter.)
3. Go to the History tab in ZAP, select this request and right-click on "Break...". Now it looks like this:

![add_breakpoint](https://user-images.githubusercontent.com/72920563/99229271-143a5900-27ee-11eb-9390-0cc8b8ebbb66.png)

Now this breakpoint will not that work. The correct String should be `http://192.168.56.1:8000/search/\?q\=test` instead of `http://192.168.56.1:8000/\?q\=test`.

**Software versions**
 - ZAP: 2.9.0
 - Arch Linux
 - Browser: Firefox 82.0.3

**Comment by t4skforce** [comment]
The issue is not really in Breakpoint generation menu it actually is an issue in the site structure detection

`curl -x http://localhost:8080 -k -L 'http://127.0.0.1/search/?q=test'`
builds a site tree that recognizes "search" as endpoint and not as folder

whereas
`curl -x http://localhost:8080 -k -L 'http://127.0.0.1/search/index.html?q=test'`
is detecting "search" correctly as folder

@kingthorin @thc202 @psiinon is this intended behavior or actually a site structure bug and "" (empty string) should be detected as endpoint and "search" as folder?

![image](https://user-images.githubusercontent.com/7422037/99643381-e43cc100-2a4c-11eb-9169-376ac41f2342.png)

**Comment by psiinon** [comment]
Updated the title to reflect the underlying problem.
This will mean that we loose information about an app and therefore might not attack it as effectively as we should.
