### ISSUE TITLE
VulnCheck Extension not working

### ISSUE THREAD

**Issue by theamanrawat** [zaproxy/zaproxy#6364]
Hi, VulCheck Extension needs to be update or should be remove.

# Steps to reproduce

1. Open ZAP with VulCheck Extension.
2. Go to tools > VulCheck.
3. Enter `wordpress` OR name of any vendor.
4. Check any one option and click Search

Nothing happens in Text box on right side.

Console output is this.
```
java.lang.NullPointerException
	at org.zaproxy.zap.extension.vulncheck.VulnChecker.getCve(VulnChecker.java:62)
	at org.zaproxy.zap.extension.vulncheck.VulnCheckerFrame$4.actionPerformed(VulnCheckerFrame.java:128)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
```

**Comment by kingthorin** [comment]
I vote for also removing it as we did for wafp (cmss). The person who created it is no longer contributing, we don’t have details for updating its DB, along with this issue.

**Comment by theamanrawat** [comment]
Yeah it's better to remove. May I create pull request for this?

**Comment by kingthorin** [comment]
Let’s get agreement from at least one other core team member first.

**Comment by theamanrawat** [comment]
Cool :relaxed:

**Comment by psiinon** [comment]
I agree :)

**Comment by kingthorin** [comment]
@theamanrawat please go ahead with a PR.

**Comment by theamanrawat** [comment]
@kingthorin , I created new branch `VulnCheck-remove` and while making pull request these changes are showing in my previous pull request like this.

![Screenshot 2020-12-17 201013](https://user-images.githubusercontent.com/35992750/102502032-238a1c00-40a4-11eb-99de-59cfeb8c62ea.png)

**Comment by thc202** [comment]
You need to create the new branch from master upstream, since you already have changes in your local master branch. You can also interactive rebase against upstream/master and remove the first commit.

**Comment by kingthorin** [comment]
All of the following assumes that "origin" is your fork.

Here's what you need to do at the cli from within your zap-extensions repo directory:
```bash
git fetch upstream
git reset --hard upstream/master
git push
```

That will bring both your local and origin copies back to current. Note: In this case you to a hard reset to abandon the changes and get things back to normal. If your `git push` fails with a not fast forward error then just `git push --force` since technically it might be ahead due to pushing your other changes.

Then you'll need to make a feature branch to do your work on:
```bash
git checkout -b rem-vulncheck
```

Do your changes, commit them, push them, open a PR.

If you want to work on something else at the same time then `git checkout master` to go back to master and create a new branch for whatever other changes.

In the normal course of things in order to keep your local copy and origin up-to-date. Ensure you've got master (or whatever the default is) checked out, get the latest state of the upstream, merge the upstream changes, and push them to origin.
```bash
git checkout master
git fetch upstream
git merge upstream/master
git push
```

**Comment by theamanrawat** [comment]
Thank you so much to both of you :smile:

https://github.com/zaproxy/zap-extensions/pull/2658
