### ISSUE TITLE
OpenApi add-on: multipart form-data support 

### ISSUE THREAD

**Issue by hideintheclouds** [zaproxy/zaproxy#6418]
ZAP does not seem to support paths with multipart form-data in an OpenApi/Swagger specification.

In order to illustrate the issue, I have taken the petstore Swagger (https://petstore.swagger.io/v2/swagger.json), imported it into the Editor (https://editor.swagger.io/) and converted it to an OpenApi definition.
I have actually tried both Swagger(v2) and OpenApi(v3) and there seem to be the same behaviour.

Inside the Petstore definition, there is a POST operation to upload an image using multipart form-data for a file.

Now, the problem lies when importing this openapi into ZAP, as it does not seem to properly identify/attack the parameters from the multipart form-data (note there is no Content-Type and the body is empty):
![image](https://user-images.githubusercontent.com/9388089/105751128-e2f4ac80-5f45-11eb-991c-fec371751c55.png)
f a call is made to this path using a client (i.e. Postman) and having ZAP in proxy mode, then ZAP will correctly show the Content-Type and show the proper body with boundaries and Content-Disposition.

Example:
Header
_Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW_

Body:
_------WebKitFormBoundary7MA4YWxkTrZu0gW--,------WebKitFormBoundary7MA4YWxkTrZu0gW--
Content-Disposition: form-data; name="file"; filename="/test.txt

------WebKitFormBoundary7MA4YWxkTrZu0gW--_

Note: ZAP has the Multipart Form-data input vector enabled in the Active scan, but there seem to be no difference in properly identifying the multipart form-data parameters and being able to attack them.

At the moment, the only way of scanning multipart form-data requests in OpenApi is to proxy them thorough ZAP, and not use the openapi add-on.

**Comment by pranavsaxena17** [comment]
I'll like to pick this up. Any pointers @thc202 @kingthorin ?

**Comment by kingthorin** [comment]
The OpenAPI add-on is here: https://github.com/zaproxy/zap-extensions/tree/master/addOns/openapi

You’ll need to make (or get) an OpenAPI definition that uses multi-part form data and add handling for it, including unit tests (they’re in the same location).

**Comment by pranavsaxena17** [comment]
There are a couple of decisions to make regarding this about which I am unsure:-

1) How should the boundary used to separate the various parts of the request be generated?(should it be random or constant). Normally, the user agent generates a random boundary for each multipart request, so as to ensure that the probability of the boundary being present in the user data be astronomically low.  However, in this case since the "user data" is known to us and is constant for every type of request we make, having a constant boundary should do as it serves the purpose of enabling us to distinguish the various parts of the request. Having a random boundary would also make the tests somewhat messier. Hence I'm leaning towards the latter on this one.

2) What should I take as an example of a generic text file and a generic image file. The contents of the files don't matter, I just need  them as sample data to send when the request requires so. For the text file, I initially thought of taking the README, but that seems to be unnecessarily large, as the same purpose can be achieved with a file containing a single line. So, should I make a new file for this, or use the README(or perhaps another file which is already present). For the image file, should I take the zap icon, os soething else?

Your thoughts on these would be helpful @kingthorin @thc202 @ricekot @psiinon

**Comment by kingthorin** [comment]
I'd say just create a text file that has some [lorem ipsum](https://www.lipsum.com/) in it:
```text
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu tortor efficitur, ultricies augue ut, gravida mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce vitae odio pellentesque, molestie enim a, aliquam ligula. Suspendisse congue cursus tortor, porttitor semper nisl auctor vel. Duis non est nec leo pharetra ultricies. In hac habitasse platea dictumst. Maecenas nunc odio, mollis non magna quis, congue maximus ex. Aliquam erat volutpat. 
```

For an image, using a zap icon or image is a great idea.

**Comment by thc202** [comment]
It's not necessary to create actual files, hardcoded (dummy) content should do it.

For the boundary, better random IMO. The tests shouldn't need to verify the actual value of the boundary.

**Comment by pranavsaxena17** [comment]
@thc202 @kingthorin  The tests verify the request body, and that inevitably contains the boundary as well. If I take a completely random boundary, it would be impossible to parse the request body and consider only the required parts. A solution could be something semi-random like "ZAPMultipartBoundary(RandomAlphaNumericString)", though even that would require quite a lot of parsing in the tests.

**Comment by thc202** [comment]
The tests can just check that the contents of the "files" are present, in any case the structure can be validated easily (see variant that handles multipart).
