### ISSUE TITLE
OWASP Benchmark Test Freezes on V2.10

### ISSUE THREAD

**Issue by AbhishekPuranam** [zaproxy/zaproxy#6470]
when i try to run a OWASP Benchmark test on ZAP V2.10. It freezes. I have set JVM to 4GB, still it freezes. I have also gone through the feedback provided by OWASP benchmark. If some has completed can, please do share the report.

**Comment by thc202** [comment]
Please provide a thread dump when that happens.

**Comment by AbhishekPuranam** [comment]
@thc202 :Trying to fetch it, but system freezes. I am running on Windows. I see in another thread you have done for V2.6. Will there be a major change in values between V2.6 and V2.10

**Comment by I3urny** [comment]
I ran ZAP V2.10 against OWASP Benchmark v1.2 without increasing the JVM memory and didn't have any issues with ZAP. The Benchmark on the other hand got stuck at some point during the scan. I only restarted the Benchmark application so that the scan could continue. 

My .xml report can be found [here](https://gist.github.com/I3urny/0adccab64e6a38804235988fd5faa52a)

**Comment by AbhishekPuranam** [comment]
Hi @I3urny : What is the score you got. It completed scan for me. I got a score of 9%
https://github.com/AbhishekPuranam/OWASP-ZAP-Benchmark-/tree/v2.10

**Comment by I3urny** [comment]
I got a score of 8% but you can just plug my result .xml into the Benchmark project to see the exact results. 

Back to the original issue of this ticket: you ran ZAP again and it did not freeze that time? And just out of curiosity, how long did the scan take?

**Comment by thc202** [comment]
Closing, no evidence there's an issue with ZAP.
