### ISSUE TITLE
Request for UBI based ZAP proxy container image

### ISSUE THREAD

**Issue by skairali** [zaproxy/zaproxy#6485]
**Is your feature request related to a problem? Please describe.**
Current ZAP container image which is based on ubuntu is putting us in position to fix lots of vulnerabilities because of the broader nature of base image

**Describe the solution you'd like**
We are in need of ZAP image which is based on UBI base image (https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image).

**Describe alternatives you've considered**
UBI is our requirement. 

**Additional context**
NA

**Would you like to help implementing this feature?**
Please let us know if any help is required

**Comment by kingthorin** [comment]
Can't you just look at the existing image creation scripts and create whatever image you want/need?

**Comment by psiinon** [comment]
What benefit does this bring to us or other ZAP users?
The ZAP docker images are well established and well used.
I cant imagine us changing the base image without some good reasons.

**Comment by skairali** [comment]
@psiinon  The ask is not to change the base image.  The current base image is based on generic Ubuntu which makes the image bulky in terms of size and all sorts of vulnerabilities are poping up in regular scans. So would be great to get a more Skinny version of base image  as an option ( not as a replacement of original base image).  UBI would greatly aid a lot of users who are using UBI based solutions especially on IBM Cloud based deployments etc..

**Comment by psiinon** [comment]
We're already maintaining 4 docker images. An additional base option would double that to 8. What happens when someone else wants us to maintain another base image for some other reason - do we then support 12 or 16?
We are a relatively small team so I think we should only support one base image. I'm not against changing the current one but we know that lots of people seem very happy with the current images. We would have to be sure that changing was the right way to go for the majority of our users.
I cant see that being a priority right now, but if lots of people start commenting on this issue that they'd like us to change then that could increase the chance that we'd look at it.

**Comment by kingthorin** [comment]
Note if you really have size concerns you can switch to the existing `bare` image.

**Comment by skairali** [comment]
Our requirement is to have UBI image not just a skinny image.  We will look into existing scripts.   Do you think this is something we can contribute back?

**Comment by kingthorin** [comment]
Hi @skairali I think the team would be willing to link to your repo (or whatever) for the UBI, however we don't really need another thing to produce or maintain going forward.

**Comment by thc202** [comment]
Closing per previous comment.

Feel free to leave a comment (or use the dev mailing list) if you end up creating the image.
