### ISSUE TITLE
Base64 rule (10094) should ignore base64 in headers

### ISSUE THREAD

**Issue by omerlh** [zaproxy/zaproxy#6619]
**Describe the bug**
The base64 scanners report on base64 in the HTTP headers, where it makes sense to use them.

I think it's either need to ignore the headers, or somehow have an option to ignore them.

**Screenshots**
![image](https://user-images.githubusercontent.com/6730584/119251582-e6283e00-bbaf-11eb-9b76-7349a89e2bd9.png)

**Software versions**
 - ZAP: 2.10.0
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://www.zaproxy.org/faq/how-do-i-see-what-version-of-an-add-on-extension-i-have-installed/]
![image](https://user-images.githubusercontent.com/6730584/119251517-98abd100-bbaf-11eb-88e5-e6e21e76ea3e.png)
 - OS: Mac

**Comment by drewrad8** [comment]
It would be better as an option (rather than completely ignoring base64 in the header), since some basic authentication methods store user/pass in the headers as base64

**Comment by kingthorin** [comment]
```java
@Test
void test6619() throws URIException, HttpMalformedHeaderException, NullPointerException {
    // Given
    HttpMessage msg = new HttpMessage(new URI("https://example.com/", false));
    msg.getResponseHeader().addHeader("ETag", "W/\"45cd-7MlSATHznbvb7qdGT+/VL6oqXM\"");
    // When
    scanHttpResponseReceive(msg);
    // Then
    assertThat(alertsRaised.size(), equalTo(1));
}
```

**Comment by kingthorin** [comment]
I propose we do something similar to: https://github.com/zaproxy/zap-extensions/blob/b22dad79e39e3248f5cfe09151002441c7febdb1/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRule.java#L76-L89

I'd suggest we start with `ETag` as noted here. Plus `Authorization` as well as `X-ChromeLogger-Data` and `X-ChromePhp-Data` because those are covered by other rules.
