### ISSUE TITLE
Reports are not generated unless autooff is used

### ISSUE THREAD

**Issue by pennal** [zaproxy/zaproxy#6903]
**Describe the bug**
With the latest release of the docker image, the baseline scan does not generate the reports unless the `--autooff` flag is used.

I believe this is related to the [Baseline scan changes](https://www.zaproxy.org/blog/2021-06-15-baseline-scan-changes/) previously announced, although they shouldn't have caused any issues with the reports.

I checked the source code as suggested, but I can't see why the reports should not be generated.

**To Reproduce**
1. Run `docker run --name owasp -v $(pwd)/test-zap:/zap/wrk:rw --rm -i -t owasp/zap2docker-stable zap-baseline.py -t https://start.spring.io -d -r report.html -J report.json` => No report is generated in the mounted folder
2. Run `docker run --name owasp -v $(pwd)/test-zap:/zap/wrk:rw --rm -i -t owasp/zap2docker-stable zap-baseline.py -t https://start.spring.io -d -r report.html -J report.json --autooff` => Reports are successfully generated 

**Expected behavior**
Two reports should be generated in the mounted folder. One in JSON format, the other in HTML format , even when not using the `--autooff` flag

**Software versions**
Using ZAP inside of the `owasp/zap2docker-stable` docker image. 

SHA: owasp/zap2docker-stable@sha256:461cfec7f6ce3c6ce7a8aceef773ed482d6ee572a16f1e6e86bd78799ae483cf

**Would you like to help fix this issue?**
No

**Comment by psiinon** [comment]
This might not just be limited to reports - the zaproxy.org baseline scan is failing as well: https://github.com/zaproxy/zaproxy-website/runs/4090545716?check_suite_focus=true
I'm not sure whats going on yet but it could be a problem mounting the directory...

**Comment by psiinon** [comment]
We think we know whats going on and hope to have a work around asap.
And then a proper fix once we've had a chance to test it thoroughly...

**Comment by psiinon** [comment]
OK, we've updated the stable release and it works ok for me.
Please let me know if it works for you.
This is actually another temp work around - we need to put a full fix in place so we'll be leaving the issue open until thats in place.

**Comment by pennal** [comment]
I can confirm it works now, also when omitting the `--autooff` flag.

Using `owasp/zap2docker-stable@sha256:9c76255f2c1ac2f5137f5086fbb6e24781f1c0e98fb7b2168f631140b356d39e`

Will test again once the proper fix has been implemented. Thanks!

**Comment by psiinon** [comment]
OK, the full fix is implemented in https://github.com/zaproxy/zaproxy/pull/6904
The problem was due to the fact we recently release a new version of the automation framework (AF) add-on.
We've had a problem where the AF was updating add-ons including itself - the add-on got unloaded and lost all state.
The previous fix was to always use the `-addonupdate` ZAP option .. but it turns out that then the AF looses the relevant command line options and therefore doesnt run the plan (which it no longer knows about).
The latest fix runs ZAP once to update any add-ons and then a second time to run the job.
We're still looking into how we can get the AF to update itself gracefully but that will nbe non trivial.
We've updated the stable image with the fix, but this will now have the latest AF version and so wouldnt hit this problem anyway.
But now when we do issue a new AF then it shouldnt break...
