### ISSUE TITLE
requestor job to support additional headers

### ISSUE THREAD

**Issue by tmfjr** [zaproxy/zaproxy#6917]
This is a note from Simon - Please raise an enhancement request issue for the requestor job to support additional headers - these should support env vars which will allow you to specify the bearer token.

This is the issue / feature I would request:

I set up a requestor for a valid request that I captured. The requestor does not let me add the bearer token needed for authorization.

For example, this is the request as captured:
```
POST https://api.mydomain.com/search HTTP/1.1
Content-Type: application/json
Authorization: Bearer <A Bunch of data that represents the token...>
Content-Length: 162
Host: api.mydomain .com
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.12)

{<SOME DATA>}
```
The request job in the yaml looks like this:
```yaml
jobs:
- parameters:
    user: ""
  requests:
  - url: "https://api.mydomain.com/search"
    name: ""
    method: "POST"
    data: "{<SOME DATA>}"
    responseCode: 200
  name: "requestor"
  type: "requestor"
```
Can I somehow paste the valid token in the yaml file? If so what is the syntax?

**Comment by njmulsqb** [comment]
Hi @psiinon, assign this issue to me!

**Comment by njmulsqb** [comment]
I am using my company's laptop on which I don't have admin rights, so when I try to run `zap.bat` using `-cmd` flag to generate yml file, it fails because it doesn't have write permissions in the working directory.

I am trying to explore automation framework and understand it before actually starting to work on this issue, now my question is, how can I use automation framework on building ZAP myself? Like I can build ZAP using IntelliJ but where can I locate the `zap.bat` file in cloned repository  and play with its functionality?

**Comment by kingthorin** [comment]
Just run ZAP from within the IDE and pass the necessary switches. I’m sure you can do it with IntelliJ … in Eclipse it’s called a run configuration.

**Comment by thc202** [comment]
It's called the same in IntelliJ IDEA: https://www.zaproxy.org/docs/developer/building-zap-with-intellij-idea/ and should be added to "Program arguments".

**Comment by njmulsqb** [comment]
Hi,

I spent some time today on this issue and I have some concerns, I first assumed that requestor job is handled using cmd line so in order to see the flags/switches that are used to configure requestor job I checked the documentation https://www.zaproxy.org/docs/desktop/addons/requester/
https://www.zaproxy.org/docs/desktop/addons/automation-framework/job-requestor/
but no such information is provided there. I get the point that it is used to send custom requests to the target URL but how can we get the cmdline do this task? How to generate the config yaml file for it?

What I have understood this enhancement is about, is that if a user gives custom headers under ` - parameters : ` in the yaml file, it also gets sent by the requestor job? Right?

In one of the tutorials on YouTube, I saw @psiinon using GUI automation framework tab, so I went there and saw the requestor job button there which includes GUI form to make requestor job. 
![image](https://user-images.githubusercontent.com/47940898/163708967-a29c31d7-bbde-476d-ac71-37eecb5e0d16.png)
Do I need to work with it too or just focus on cmd version? If I need to work on GUI, do I need to add some sort of button that adds input fields dynamically in order for the user to add custom headers?

I looked for relevant code in the zap source and there are 100s of instances of requestor and automation framework, can you tell me exact in which file am I supposed to make changes? It will make life a lot easier for me.

Thanks

**Comment by psiinon** [comment]
Ideally the GUI would be supported as well. We can point you to the relevant files, but tbh its good experience to learn to find what needs to be changed yourself. For anything involving the GUI then you can search for strings that appear in the relevant dialogs - you should find them in a language file, from which you'll get a key which you can search for in the code. You should be able to work back from the GUI to the code which handles the relevant job from the command line.

**Comment by njmulsqb** [comment]
Hi,

I have analyzed the code and it has started making some sense now, for example, as you asked each job has its own class under the `org/zaproxy/addon/automation/jobs` sections and here lives the `RequestorJob.java` file.

The solution I am preparing up in my mind looks something like, we should include the additional headers under some custom field in yaml file, and the file responsible for handling those fields and sending requests will be changed. Is it true?

The RequestorJob will read the additional headers from yaml and will include it in the HTTP request being sent. Right?

**Comment by psiinon** [comment]
Thats the one and that sounds like a good plan :)
Note that the GUI for it is [RequestorJobDialog.java](https://github.com/zaproxy/zap-extensions/blob/main/addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/RequestorJobDialog.java)

**Comment by njmulsqb** [comment]
Yes, I have seen the GUI directory as well but I am first planning to implement this on CLI and then I will see how can I deal with GUI.

The updated YAML file will look something like this 
```
jobs:
- parameters:
    user: ""
  requests:
  - url: "https://njmulsqb.github.io"
    name: ""
    method: "GET"
    data: ""
    headers: "header1:value1,header2:value2,header3:value3"
    responseCode: 200
  name: "requestor"
  type: "requestor"

```
The custom headers will be in key:value pairs and will be comma separated.

Now, I would need a little help to locate the implementation point. I see that the function `runJob` is handling the requestor job and I need to add my custom header handling code in it, but first I need to handle reading the headers field from YAML file.
https://github.com/njmulsqb/zap-extensions/blob/f3b307d326e6ff61f02af23c6ea472c4fb016892/addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/RequestorJob.java#L132-L134
In the code above, `data` variable is being iterated over, apparently all the requests are available in this variable, so I need to locate where this data is coming from.

Here's the constructor that's setting the data variable
https://github.com/njmulsqb/zap-extensions/blob/f3b307d326e6ff61f02af23c6ea472c4fb016892/addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/RequestorJob.java#L62-L64
but I am having hard time to examine where this `parameters` argument is coming from, probably it contains the data I am interested in. Can you help me here?

Also, I believe I dont need to make changes in `AutomationEnvironment` as I am not tweaking with env variables.

The files currently I believe needs to be changed are:
- RequestorJob.Java
- The file thats dealing with YAML reading stuff
- The changelog

Is there anything I am missing out?

Also, one generic question, am I reverse engineering the code's logic the right way or am I going into a rabbit hole and wasting lots of time? 

Thank you :)

**Comment by njmulsqb** [comment]
One more thing, it maybe is irrelevant but I am receiving quite a lot of emails stating. 
![image](https://user-images.githubusercontent.com/47940898/167196298-7b267afb-96e3-4ac0-a102-a09dac3edfea.png)
How can I stop this?

**Comment by kingthorin** [comment]
Disable actions in your fork.

**Comment by njmulsqb** [comment]
> It is irrelevant 😉 But you can: Disable actions in your fork. ![image](https://user-images.githubusercontent.com/7570458/167197077-d5ed4818-ddde-489e-ad28-e44ed30c7a48.png)

haha sorry for being irrelevant, should have asked in IRC. 
Disabled.

**Comment by kingthorin** [comment]
`    headers: "header1:value1,header2:value2,header3:value3"`

Why not use a standard yaml array?
```yml
headers:
  header1:value1
  header2:value2
  header3:value3
```

**Comment by njmulsqb** [comment]
> ` headers: "header1:value1,header2:value2,header3:value3"`
> 
> Why not use a standard yaml array?
> 
> ```yaml
> headers:
>   header1:value1
>   header2:value2
>   header3:value3
> ```

Sounds better.

**Comment by njmulsqb** [comment]
Hi @psiinon 
Can you help with the queries? I want to work on this issue on this weekend

**Comment by thc202** [comment]
> The file thats dealing with YAML reading stuff

The existing code already provides the data, you just need to process it (check`RequesterJob#verifyParameters`), the headers would have to be added to `Request`.

**Comment by njmulsqb** [comment]
Hi all,
Here is the tweaks I have made so far in RequestorJob.java: https://github.com/njmulsqb/zap-extensions/blob/feature-custom-headers/addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/RequestorJob.java

I am stuck at a problem an would need a nudge. To understand the code flow I am using debugger to see what data is flowing around in the variables.
The method `verifyParameters()` is accepting the jobData, if I put the breakpoint at line:92
 ```
                JobUtils.applyParamsToObject(
                        (LinkedHashMap<?, ?>) request, req, this.getName(), null, progress);
```

I can see that `req` is containing the custom headers read from the YAML file, and after reading the code of `applyParamsToObject` I understood that this method is using the data and pasting it into the object being passed using the object's setters defined in the class so I added data member and methods (getter/setters) in the Request class so that when new headers are read, `applyParamsToObject` will call its setter and then it should be added into the `Request's object`.
But, when I run the code again, I cant see the headers being added into the object and an error is being thrown `automation.error.options.unknown="Unrecognised parameter for job requestor: headers"`

Now this error is being used at many places, and I cant see whats causing this error.

Currently, I am assuming that Request's constructor need not to be modified as only the setters are being called to set the values to the object, but definitely constructor needs to be modified which I tried but resulted in ripple errors in ReTestPlan file. Generously, @thc202 gave me some hints on this that I should make a separate constructor for passing the additional argument of headers but this seems to be just a workaround.

But currently my goal is to include the headers in to the Request object properly, without causing errors/warnings.

Thanks

**Comment by njmulsqb** [comment]
Plus, I think things would have been easier if each file has a comment in the beginning about what is it doing, also in my fork, I am considering to write a comment with some function calls that needs explanation, is it okay? Can these comments be added to ZAP?

**Comment by njmulsqb** [comment]
Hi, can anyone answer the above two queries? It's been a while. Thanks!

**Comment by thc202** [comment]
> an error is being thrown

You need to provide more details, the `JobUtils` is able to copy `List`.

> but this seems to be just a workaround.

No, it's not a workaround it's what needs to be done, otherwise you are breaking other add-ons that are using that constructor.

> Can these comments be added to ZAP?

Make sure it's proper JavaDoc rather than plain code comments though.

**Comment by njmulsqb** [comment]
> Make sure it's proper JavaDoc rather than plain code comments though.
```
for (Object request : requests) { /** Iterating through each request in requests arrayList */
            if (request instanceof LinkedHashMap<?, ?>) { /** Checking if type of request is LinkedHashMap, <k,v> could be of any type */
```
Does this look fine to you?

**Comment by njmulsqb** [comment]
I took some time to understand where I left last time and got the point why I left :D this issue is really annoying me.
To put it in simple wordings, I have added getter/setter for headers named `getHeaders` and `setHeaders` respectively so `Request` class now has these headers so when we call `getMethods()` on this class it should return the new headers, right?
But when `getMethods()` is called on Request object, it returns all the previously declared methods but not the new ones that I am writing in Request class, its a lame and not-so-usual issue but I have banged my head around this a lot now, the `getMethods()` should return all the methods why isn't it skipping the new ones? Any ideas?
![image](https://user-images.githubusercontent.com/47940898/191488670-0e1e93f4-2459-4466-9c3c-f1deb069807e.png)
Here are the methods I have added in Request class 
![image](https://user-images.githubusercontent.com/47940898/191488848-9a39a2ac-4e2d-422f-8ebf-bf0fd0f308eb.png)

**Comment by njmulsqb** [comment]
So as discussed in IRC channel, the solution to above issue is that I wasn't deploying the changes to Zap Add on, each code change needs to be replicated to the addon file as zap reads the changes from addon file. 
The solution is to run `gradlew addOns:automation:copyZapAddOn` when Zap changes needs to be deployed.
This needs to be run whenever I want to see the changes.
To check if the addon is deployed properly or not, go to zap --> addons --> automation --> click on it and see where the plugins are being stored, go to that directory and check if the addon file (automation-beta) in this case has updated or not?

**Comment by njmulsqb** [comment]
Hi,

I have created a PR https://github.com/zaproxy/zap-extensions/pull/4052 that contains an implementation of this feature. I expect some improvements and code changes also the GUI needs to be implemented yet. The additional headers are being read from YAML file and is being added into the HTTP message so basic functionality is implemented. Looking forward to feedback!
