### ISSUE TITLE
OAST: Interactsh: correlationId with prefix characters needs a dot as separator

### ISSUE THREAD

**Issue by denniskniep** [zaproxy/zaproxy#7003]
**Is your feature request related to a problem? Please describe.**
Interactsh parses the incoming DNS Name, URL etc. and tries to extract a correlationId. But a dot between arbitrary prefixing characters and the correlationId is required.

* Does **not** work: `abc<correlationId>.interact.sh` ->  `abc123456789.interact.sh`
* Does work: `abc.<correlationId>.interact.sh` ->  `abc.123456789.interact.sh`

[getNewPayload()](https://github.com/zaproxy/zap-extensions/blob/d6e99ec1fff05a28c5aa7256a93aa6427c44ed34/addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshService.java#L290) does not consider this currently.

**Describe the solution you'd like**
We should implement that in a general way and append a single character with a dot in front of the correlationId

**Additional context**
https://github.com/zaproxy/zap-extensions/pull/3427

**Would you like to help implementing this feature?**
yes

**Comment by kingthorin** [comment]
I’d suggest allowing any arbitrary string before the dot, maybe defaulting to a single character. Just to be a bit future proof for whatever next usage pattern we can’t predict.

**Comment by thc202** [comment]
If more is needed it can simply be added to the returned payload.

**Comment by denniskniep** [comment]
The problem is, that it is not really obvious that a payload needs the dot. Could lead easily to bugs or unnecessary troubleshooting for the scanner author

**Comment by ricekot** [comment]
The ZAP Interactsh client is based on the official Interactsh CLI client, which generates a payload in the format that ZAP is already using (i.e. `<correlationId><randomString>.interact.sh`):
https://github.com/projectdiscovery/interactsh/blob/c7a1b32a1a3b11aa131dd3438d85c4f4c3386cee/pkg/client/client.go#L295

Is this an Interactsh issue or a ZAP issue? The Interactsh server should be updated to understand such URLs, instead of updating all the clients.

**Comment by ricekot** [comment]
Also from the Interactsh DNS server code, it does not seem to require a dot between the correlation ID and arbitrary characters: https://github.com/projectdiscovery/interactsh/blob/c7a1b32a1a3b11aa131dd3438d85c4f4c3386cee/pkg/server/dns_server.go#L162

**Comment by thc202** [comment]
The problem is that it's splitting on dots and checking the length is 33 (the 20 + 13) https://github.com/projectdiscovery/interactsh/blob/c7a1b32a1a3b11aa131dd3438d85c4f4c3386cee/pkg/server/dns_server.go#L152 before that, so if more data is there it will not match, changing Interactsh to cope with that case might be better in the long term.

**Comment by ehsandeep** [comment]
> The problem is that it's splitting on dots and checking the length is 33 (the 20 + 13) https://github.com/projectdiscovery/interactsh/blob/c7a1b32a1a3b11aa131dd3438d85c4f4c3386cee/pkg/server/dns_server.go#L152 before that, so if more data is there it will not match, changing Interactsh to cope with that case might be better in the long term.

This is now resolved with the latest release of interactsh server, i.e [v1.0.2](https://github.com/projectdiscovery/interactsh/releases/tag/v1.0.2)
