### ISSUE TITLE
Add SSRF Scan Rule

### ISSUE THREAD

**Issue by roisec** [zaproxy/zaproxy#7360]
### Is your feature request related to a problem? Please describe.

I want the ability to do an active scan for only SSRF attacks, like SQL injection attacks.
The active scan will put oast URL on every parameter and wait for a request.

### Describe the solution you'd like

preconfigured tests for SSRF attacks

### Describe alternatives you've considered

I think it can be implemented with zap extension.

### Would you like to help fix this issue?

- [x] Yes

**Comment by kingthorin** [comment]
You can create any policy you like, with whatever combination f scan rules meets your needs.

**Comment by RoiSec** [comment]
@kingthorin ,
How can I do that?
Which rules is OAST support?

**Comment by RoiSec** [comment]
@psiinon 
I don’t see SSRF regular tests, 
For example, I want the ZAP will trying to send on every get/post parameters value, link to oast server, if the oast service detect an access then alert that. (especially for requests with this parameters.
https://github.com/1ndianl33t/Gf-Patterns/blob/master/ssrf.json)
I am say this because we already see this behavior, this could bring interesting findings.

**Comment by kingthorin** [comment]
I don’t think we would create a bundled rule to throw the payloads at every injection point.

You could look at the existing Java rules (as psiinon mentioned) and script something along with the community-script examples pretty easily though if you really think that’s what you want to do.

https://github.com/zaproxy/community-scripts/tree/main/active

**Comment by RoiSec** [comment]
I'm sorry you think so, I think it's a very important issue and it could help to Zap project.
Today, SSRF vulnerabilities are very important because of the cloud environment.
BTW burp active scan does know how to do these OAST scans.
https://portswigger.net/burp/application-security-testing/oast#:~:text=the%20target%20domain.-,OAST%20the%20easy%20way,-With%20Burp%20Collaborator

**Comment by psiinon** [comment]
And ZAP can do them too - https://www.zaproxy.org/blog/2021-08-23-oast-with-owasp-zap/
We do think its important.
But we dont just throw every possible payload against every possible injection point, that would take way too long.
Our scan rules try to be as efficient as possible, and changing all of them to use OAST is a big task and one that would take a long time.
If you would like to work on something like this (either a brand new rule or enhancing existing ones) then we're very happy to help with advice and guidance.

**Comment by RoiSec** [comment]
I agree that it to be efficient as possible and sould not delayed the CI/CD pipeline,
but ZAP currently does not have an option to do a "full scan" as I mentioned for SSRF.
@psiinon How can I help/contribute to adding a new SSRF full scan rule?

**Comment by psiinon** [comment]
ZAP does have the option to run a "full scan" just using the rules that support SSRF, you just need to create a Scan Policy that only enables those rules :)
Re creating a new scan rule - see https://www.zaproxy.org/docs/contribute/scan-rules/

**Comment by RoiSec** [comment]
Hi @psiinon , 
I am not fully understanding, I don’t found ssrf scan rule/alert type, what I need to do?
I want the ability to scan specific SSRF attack on each parameter and not whole scan of all types of attacks.

**Comment by psiinon** [comment]
As I said before - these are the rules which support OAST: https://www.zaproxy.org/alerttags/out_of_band/
If you want to use a specific SSRF attack then you will need to write your own scan rule: https://www.zaproxy.org/docs/contribute/scan-rules/
