### ISSUE TITLE
Content Cacheability Scan Rule (10049) has no example alerts

### ISSUE THREAD

**Issue by cidersage** [zaproxy/zaproxy#7502]
**- Do you want to request a *feature* or report a *bug*?**

Not really a bug; just missing information on the site.

**- What is the current behavior?**

These alerts have entries on https://www.zaproxy.org/docs/alerts/, but contain no summary, solution, or references:

Vulnerable JS Library (Powered by Retire.js) [10003](https://www.zaproxy.org/docs/alerts/10003/)
Content Cacheability [10049](https://www.zaproxy.org/docs/alerts/10049/)

**- If the current behavior is a bug, please provide the steps to reproduce.**

View the above links and try to make sense of the alerts.

**- What is the expected behavior?**

Either:

- Description of these alerts exists, OR:
- If they are no long valid, these entries are no longer present on the alerts list

**- Please mention your node.js, NPM, Hugo and operating system version.**

n/a

**Comment by psiinon** [comment]
These pages are generated from the code so the problem is not actually with the website 😄

**Comment by cidersage** [comment]
Are there any particular comments or fields that these are derived from?

**Comment by psiinon** [comment]
We have a horrible script which tries different ways to get the data https://github.com/zaproxy/zap-admin/blob/master/scripts/generate_alert_pages.js
The best rules have a "getExampleAlerts()` method which the script should read.
However that appears to be present for retire: https://github.com/zaproxy/zap-extensions/blob/main/addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java#L114-L120
So that could be a bug.
PRs to add example alerts to any scan rules are very gratefully received.
We'll look into the problem with retire ...

**Comment by psiinon** [comment]
PR which will fix the Retire example issue: https://github.com/zaproxy/zap-extensions/pull/4092

**Comment by thc202** [comment]
All being tracked in #6119.
