### ISSUE TITLE
zap-api-nodejs methods should allow for passing argument Objects

### ISSUE THREAD

**Issue by trevor-vaughan** [zaproxy/zaproxy#7608]
### Is your feature request related to a problem? Please describe.

Presently, the arguments to API calls are positional as shown in the [script.load function](https://github.com/zaproxy/zap-api-nodejs/blob/master/src/script.js#L77).

This presents a usability issue since you end up needing to pass `null` for optional arguments.

Additionally, the arguments are immediately converted into a `params` variable.

### Describe the solution you'd like

I would like to be able to pass all options as an `Object` which would be used as `params` and/or merged with the defaults if there are any.

### Describe alternatives you've considered

None.

### Additional context

I noted that the comments indicated that the code was auto-generated so I wasn't going to start working on any PRs until I had a grasp of that mechanism if it is still in use.

### Would you like to help fix this issue?

- [X] Yes

**Comment by njmulsqb** [comment]
Kindly assign this issue to me.

**Comment by njmulsqb** [comment]
Hi @trevor-vaughan 

Does this looks like something you want?
```
Script.prototype.load = function (args, callback) {
    const params = {'scriptName' : args.scriptname, 'scriptType' : args.scripttype, 'scriptEngine' : args.scriptengine, 'fileName' : args.filename};
    if (args.scriptdescription && args.scriptdescription !== null) {
      params['scriptDescription'] = args.scriptdescription;
    }
    if (args.charset && args.charset !== null) {
      params['charset'] = args.charset;
    }
    if (typeof callback === 'function') {
      this.api.request('/script/action/load/', params, callback);
      return;
    }
    return this.api.requestPromise('/script/action/load/', params);
  };
```
If yes, I have a question here, people using the API can see what arguments are being passed to the function in the current approach, but if we pass just the object, won't it become a touch difficult for them to figure out the required function arguments, seems like another usability issue to me then.

**Comment by trevor-vaughan** [comment]
@njmulsqb Thanks for picking this up!

That's pretty much what I was thinking for functionality.

In terms of API documentation, I guess there are a few options:

1. Move the `params` into the function arguments something like:
    ```javascript
    Script.prototype.load = function (params={'scriptName', 'scriptType', 'otherStuff': 'with a default'}, callback) {
    ```
    * Depending on what's being used for the API generation, it should show the defaults
    * The function string is going to get massive and pretty ugly
2. Use something like [jsdoc](https://github.com/jsdoc/jsdoc) with a [typedef](https://stackoverflow.com/a/28763616) to document each parameter and what it should be used for.
   * This is WAY better since users wouldn't have to flip-flop between the code and the API docs any longer but it's also a lot more work.
   * In theory, all of the documentation could be auto-generated as long as it matches upstream 1:1.

**Comment by trevor-vaughan** [comment]
🤔 I don't know if folks are up for this, but if we're making API-breaking changes, we can probably also drop `callback` support and just go with the `promise` code. But that's probably a separate ticket.

**Comment by njmulsqb** [comment]
@trevor-vaughan 

> That's pretty much what I was thinking for functionality.

Gotcha. I will be working on it, seems like just need to modify the arguments being passed and wherever they're used in function body.

> In terms of API documentation, I guess there are a few options: 

Yeah, 1) might result in ugly function string, 2) sounds good but I have never used these before so need to learn them and how can they be integrated to Java code, since API is being generated from Java.

>  I don't know if folks are up for this, but if we're making API-breaking changes, we can probably also drop callback support and just go with the promise code. But that's probably a separate ticket

I am definitely up for this, actually I am looking to up my JS skills so I am willing to contribute and maintain this API whenever I can, the only hindrance I feel is mental barrier that people are not using it, but checking the stats on npm have motivated me a bit. Can you explain how are you utilizing this API? 
As far as moving from callbacks to promise is concerned so I was also thinking about it, keep suggesting latest JS practices (and keep creating issues here) as they will help me to know what needs to be done on this API. Currently, I will be working on this issue, then I plan to replace the HTTP library and after that maybe we can consider replacing callbacks with promises. But since we are going for breaking changes I would request you to have a look at API and let us know what else needs to be modified/improved (coding practices, linting, tests, whatever)  so that there's minimal rework on this API and we can work on adding more functionality

**Comment by trevor-vaughan** [comment]
@njmulsqb I'm currently using it to drive the ZAP API automatically from a node.js CLI.

Being able to drive things in Node allows me to easily port it over to a web view at some point if I want to.

If you're building web apps, you're probably already doing some level of front end building with Node so adding yet another language (Python) is unnecessary.

**Comment by thc202** [comment]
> how can they be integrated to Java code

There's not much to integrate the generator just needs to output the corresponding text. It worth noting that not all parameters are documented and the actual type is not available (they will always be string right now).
