### ISSUE TITLE
Cloud Metadata scan rule uses wrong IP address

### ISSUE THREAD

**Issue by b3dd1** [zaproxy/zaproxy#7829]
See https://github.com/zaproxy/zaproxy/issues/7829#issuecomment-1509762160

--- 

### Describe the bug

When I scan owasp juice shop in attack mode I have the following request triggered:
![Screenshot from 2023-04-15 13-29-44](https://user-images.githubusercontent.com/48555849/232214526-41b7d64a-e694-4bab-a357-88e4d2a4a1aa.png)
As you can see the "Host:" header is populated with an IP address that belongs to NASA

### Steps to reproduce the behavior

Launching an automated scan against the container of juice shop

### Expected behavior

I exepect to see (as the browser shows) "Host:localhost:3000"

### Software versions

OWASP ZAP 2.12.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
It doesn’t “belong to NASA” it’s actually part of a [reserved IP space](https://search.arin.net/rdap/?query=169.254.169.254) and is purposefully used by one of the scan rules.

https://github.com/zaproxy/zap-extensions/blob/35a5e1449d1f5f7093e8afc1f6f6b426ac91e997/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CloudMetadataScanRule.java#L48

https://www.zaproxy.org/docs/alerts/90034/

**Comment by kingthorin** [comment]
You’re not wrong. I’m working on my cell and musta bungled something (fat fingers). Either way 169.154.169.254 is purposefully used by one scan rule. You can read about cloud meta data exposure via your favourite search engine.

I will re-open this because I think there’s an issue in the documentation/help for the rule in that it says 254 vs 154.

I do see that arin.net attributes 169.154 to NASA, but as you can plainly see with some research it is used by more than one cloud provider for internal metadata API endpoints.

**Comment by thc202** [comment]
It's not the docs that need to be updated.

**Comment by kingthorin** [comment]
Thanks, we might need @psiinon to double check the dns entries we setup too then.

**Comment by kingthorin** [comment]
Looks like the DNS entry is correct:

```bash
$ nslookup aws.zaproxy.org
Server:  mynetwork
Address:  192.168.2.1

Non-authoritative answer:
Name:    aws.zaproxy.org
Address:  169.254.169.254
```
