### ISSUE TITLE
Add telemetry to toolbar buttons

### ISSUE THREAD

**Issue by njmulsqb** [zaproxy/zaproxy#8375]
### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

To de-clutter the toolbar ZAP team has decided to add telemetry to the toolbar buttons to know its usage and better decide which buttons receive the most/least usage.

### Describe alternatives you've considered

Google group discussion thread: https://groups.google.com/g/zaproxy-develop/c/pjTLqdEaTlM/m/0gRkYDQTAQAJ

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
To collect stats about something like a menu click you just need to add a line like this in the relevant place:
```
Stats.incCounter("stats.ui.topmenu.open");
```

Note that the stats uploaded are defined in [ExtensionCallHome.StatsPredicate](https://github.com/zaproxy/zap-extensions/blob/main/addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java)
so that would need to be change to add `|| key.startsWith("stats.ui.")`
