### ISSUE TITLE
Latest owasp/zap2docker-weekly Image Missing `linux/amd64` Build

### ISSUE THREAD

**Issue by mike-weiner** [zaproxy/zaproxy#8440]
### Describe the bug

The latest `owasp/zap2docker-weekly` image appears to not have an `amd64` image built. Could the `linux/amd64` image get rebuilt and published? 

### Steps to reproduce the behavior

1. Visit https://hub.docker.com/r/owasp/zap2docker-weekly/tags
2. No `linux/amd64` tag listed.

### Expected behavior

I would expect to have a `linux/amd64` tag built and available to download.

### Software versions

N/A

### Screenshots

![Screenshot 2024-04-11 at 2 02 49 PM](https://github.com/zaproxy/zaproxy/assets/47571709/256dcf02-e1c9-4e9e-863d-50f29327e428)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by JohnStarich** [comment]
Interestingly, it also looks like there's only a single tagged release – no other version.

**Comment by thc202** [comment]
OWASP ZAP Docker images are no more, this should not be news:
https://www.zaproxy.org/blog/2023-08-01-zap-is-joining-the-software-security-project/#docker-hub
https://www.zaproxy.org/blog/2023-10-12-zap-2-14-0/#rebranding-and-docker-hub-move

(And many more posts in the user group and other places.)

For images that should be used: https://www.zaproxy.org/docs/docker/about/#install-instructions

**Comment by kingthorin** [comment]
Please refer to: https://www.zaproxy.org/download/#docker

As ZAP is no longer an OWASP project the images are moving away from the OWASP Docker org and will soon no longer be available there.

The images published today/this week are still a work in progress.

**Comment by JohnStarich** [comment]
Thanks @thc202. Somehow we missed the announcements.

It was a bit surprising to see previously existing image tags disappear (or drop amd64 on `latest`), which broke our builds. We'll update accordingly.

**Comment by nejch** [comment]
I'm not sure if the actual deletions were done on the OWASP side or by the zaproxy team, but just wanted to add that while moving new image deployments and tags totally makes sense to me, I find it strange to actually delete old _tagged_ images from the previous namespace rather than keeping previous releases.

At least this is how I've always seen migrations (even between different registries) done in other projects. People generally pin tagged image versions and digests with the expectation that they are immutable.
