### ISSUE TITLE
Dockerfile User Definition

### ISSUE THREAD

**Issue by cdm-anv** [zaproxy/zaproxy#8543]
### Is your feature request related to a problem? Please describe.

We have kyverno policies in place to enforce some basic security policies. When starting a zap-scan using securecodebox kyverno is blocking it because the zap-stable image does use a non-numeric USER in the docker image. 

The error message: 
Error: container has runAsNonRoot and image has non-numeric user (zap), cannot verify user is non-root (pod: \"scan-zap-auto-alertmanager-77zn5-xx 

Dockerfile does define "USER zap" only: 
https://github.com/zaproxy/zaproxy/blob/v2.15.0/docker/Dockerfile-stable

### Describe the solution you'd like

Use numeric user IDs (UIDs) and group IDs (GIDs) in zap dockerfile. 

### Describe alternatives you've considered

Currently disabling the related kyverno policy for zap. 

### Would you like to help fix this issue?

- [ ] Yes

**Comment by ricekot** [comment]
That seems like a limitation of the said policy, because the user is created in the Dockerfile with a user ID of 1000 (see [line 65 in the Dockerfile](https://github.com/zaproxy/zaproxy/blob/124b037e72072e80aa19c3860daa280267fb13be/docker/Dockerfile-stable#L65)), and a user with a UID of 1000 cannot be a root user.

**Comment by kingthorin** [comment]
https://github.com/kyverno/policies/issues/new?title=Require%20runAsNonRoot

😀

**Comment by kingthorin** [comment]
https://stackoverflow.com/a/53949466/7718222 might help too.
