### ISSUE TITLE
Server-Side Template Injection (SSTI) False Positive

### ISSUE THREAD

**Issue by tenaz3** [zaproxy/zaproxy#8622]
### Describe the bug

A Server-Side Template Injection (SSTI) vulnerability has been detected in the web application, but not the way I expected.

I ran on AttackStrength Default and HIGH, both got on this scenario.
This is happening on a variety of scan on different domains (+40)
How I can mitigate this False Positive?
Why does the scan looks only for the value `40034618` and not the entire `zjprint40034618zj` ?

### Steps to reproduce the behavior

Go to the following URL: [https://XXX.com/wp-login.php?action=bpnoaccess&bp-auth=1&redirect_to=https%3A%2F%2FXXX.ocm%2Fmembers%2Fadmin-wa%2F&wp_lang=zj%7B%7Bprint+%222712%22+%223997%22%7D%7Dzj]

The response
```
<!DOCTYPE html>
<html lang="zjprint40034618zj">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Web Academy - online platform</title>
<meta name="robots" content="max-image-preview:large, noindex, noarchive" />
</head>
</body>
</html>
```

### Expected behavior

I expected this is not a vulnerability. I had quite a lot of a false positive where the lang has the value with the print in it. 

### Software versions

Current stable and dev versions was used for this.

### Additional context

Report:

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Please, provide all the details of the alert.

**Comment by tenaz3** [comment]
@thc202 I provided the context of the alert detection

**Comment by kingthorin** [comment]
We are after the full details of the alert.

**Comment by tenaz3** [comment]
@kingthorin OK, I added the full json report with request and response

**Comment by kingthorin** [comment]
There does indeed seem to be some potential for FP based on this example. I haven't checked the code yet but the injection seems to be being matched without spaces/quotes which may indicate potential for XSS or something but doesn't necessarily mean that it was processed by a template engine. (Especially since the print statement is still included.)

<details>
<summary>Alert Details from report</summary>

```json
"alerts": [ 
    {
        "pluginid": "90035",
        "alertRef": "90035",
        "alert": "Server Side Template Injection",
        "name": "Server Side Template Injection",
        "riskcode": "3",
        "confidence": "3",
        "riskdesc": "High (High)",
        "desc": "<p>When the user input is inserted in the template instead of being used as argument in rendering is evaluated by the template engine. Depending on the template engine it can lead to remote code execution.</p>",
        "instances":[ 
            {
                "uri": "https://platform.web-academy.com.ua/wp-login.php?action=bpnoaccess&bp-auth=1&redirect_to=https%3A%2F%2Fplatform.web-academy.com.ua%2Fmembers%2Fadmin-wa%2F&wp_lang=%22%7Dzj%7B%7Bprint+%223866%22+%228445%22%7D%7Dzj",
                "method": "GET",
                "param": "wp_lang",
                "attack": "\"}zj{{print \"3866\" \"8445\"}}zj",
                "evidence": "",
                "otherinfo": "Proof found at [https://platform.web-academy.com.ua/wp-login.php?action=bpnoaccess&bp-auth=1&redirect_to=https%3A%2F%2Fplatform.web-academy.com.ua%2Fmembers%2Fadmin-wa%2F&wp_lang=zj%7B%7Bprint+%222712%22+%223997%22%7D%7Dzj]\ncontent:\n[<!DOCTYPE html>\n<html lang=\"zjprint38668445zj\">\n<head>\n<-- truncated -->
                "request-header": "GET https://platform.web-academy.com.ua/wp-login.php?action=bpnoaccess&bp-auth=1&redirect_to=https%3A%2F%2Fplatform.web-academy.com.ua%2Fmembers%2Fadmin-wa%2F&wp_lang=%22%7Dzj%7B%7Bprint+%223866%22+%228445%22%7D%7Dzj HTTP/1.1\r\nhost: platform.web-academy.com.ua\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8\r\nAccept-Language: en-US,en;q=0.5\r\nConnection: keep-alive\r\nUpgrade-Insecure-Requests: 1\r\nSec-Fetch-Dest: document\r\nSec-Fetch-Mode: navigate\r\nSec-Fetch-Site: none\r\nSec-Fetch-User: ?1\r\nPriority: u=0, i\r\n\r\n",
                "request-body": "",
                "response-header": "HTTP/1.1 200 OK\r\nDate: Wed, 04 Sep 2024 13:08:38 GMT\r\nContent-Type: text/html; charset=UTF-8\r\nConnection: keep-alive\r\nx-powered-by: PHP/7.4.33\r\nexpires: Wed, 11 Jan 1984 05:00:00 GMT\r\ncache-control: no-cache, must-revalidate, max-age=0\r\nset-cookie: wordpress_test_cookie=WP%20Cookie%20check; path=/; secure\r\nset-cookie: wp_lang=%5C%22%7Dzj%7B%7Bprint%20%5C%223866%5C%22%20%5C%228445%5C%22%7D%7Dzj; path=/; secure\r\nx-frame-options: SAMEORIGIN\r\nreferrer-policy: strict-origin-when-cross-origin\r\nvary: Accept-Encoding\r\nplatform: hostinger\r\npanel: hpanel\r\ncontent-security-policy: upgrade-insecure-requests\r\nx-turbo-charged-by: LiteSpeed\r\nCF-Cache-Status: DYNAMIC\r\nReport-To: {\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=zLFV6QBkSxWaztelhjUI1u9XGl2Sw96VJI5gNuno8wnJY407RTNF5wxUxKQFTMl4T1Ndp5PSWsHeraXloBejJUKQKOAwNUBa5RAWkPFe%2BlW1zkIH5%2BWZ2vFcYBnFYJLosDBNXHbcyqcwqlRdR78%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}\r\nNEL: {\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}\r\nServer: cloudflare\r\nCF-RAY: 8bde3593f9646d3a-GIG\r\nalt-svc: h3=\":443\"; ma=86400\r\ncontent-length: 101191\r\n\r\n",
                "response-body": "<!DOCTYPE html>\n<html lang=\"zjprint38668445zj\">\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<title>Web Academy - online platform</title>\n<-- truncated -->
            }
        ],
        "count": "1",
        "solution": "<p>Instead of inserting the user input in the template, use it as rendering argument.</p>",
        "otherinfo": "<p>Proof found at [https://platform.web-academy.com.ua/wp-login.php?action=bpnoaccess&bp-auth=1&redirect_to=https%3A%2F%2Fplatform.web-academy.com.ua%2Fmembers%2Fadmin-wa%2F&wp_lang=zj%7B%7Bprint+%222712%22+%223997%22%7D%7Dzj]</p><p>content:</p><p>[<!DOCTYPE html></p><p><html lang=\"zjprint38668445zj\"><-- truncated -->",
        "reference": "<p>https://portswigger.net/blog/server-side-template-injection</p>",
        "cweid": "1336",
        "wascid": "20",
        "sourceid": "446",
        "tags":[ 
            {
                "tag": "OWASP_2017_A01",
                "link": "https:\/\/owasp.org\/www-project-top-ten\/2017\/A1_2017-Injection.html"
            },
            {
                "tag": "OWASP_2021_A03",
                "link": "https:\/\/owasp.org\/Top10\/A03_2021-Injection\/"
            },
            {
                "tag": "CWE-1336",
                "link": "https:\/\/cwe.mitre.org\/data\/definitions\/1336.html"
            },
            {
                "tag": "WSTG-v42-INPV-18",
                "link": "https:\/\/owasp.org\/www-project-web-security-testing-guide\/v42\/4-Web_Application_Security_Testing\/07-Input_Validation_Testing\/18-Testing_for_Server-side_Template_Injection"
            }
        ]
    }
]

```

</details>

**Comment by tenaz3** [comment]
@kingthorin if you can delete the data and we share the information privately I appreciate.

**Comment by tenaz3** [comment]
@kingthorin did you have the change to look on the issue?

**Comment by kingthorin** [comment]
I think I might see an issue based on what you'd shared. I need to dig into the code.

**Comment by tenaz3** [comment]
@kingthorin Have you been able to identify the issue, or would you like more details?

**Comment by kingthorin** [comment]
Thanks for checking in. Unfortunately due to an injury I haven't been able to dig into it yet.

**Comment by rbliss** [comment]
Hey @kingthorin, sorry to hear about your injury. I hope you get feeling better soon! Also, congratulations on the Checkmarx move :) 

I'm chiming in here with more data to help elucidate what I think is going on. With our clients, it appears that about 80% of the SSTI findings come from one particular check: [the GoTemplateFormat](https://github.com/zaproxy/zap-extensions/blob/main/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ssti/GoTemplateFormat.java).

The GoTemplateFormat checks for a concatenation of two numbers instead of a math operation like the template tests. It appears to generates FPs far more frequently due to how web apps tend to place input parameters into the page while filtering special characters. For example, here's the first 3 SSTI alerts I looked at from different sites:

Attack: `zj{{print "6518" "7178"}}zj`
Proof (from page): `"is_analytics_enabled":"1","is_search":"1","is_id":"zjprint65187178zj","is_label":"","is_cat":"Results Found"}`

Attack `zj{{print "7996" "3057"}}zj`
Proof (from page): `<!DOCTYPE html> <html lang="zjprint79963057zj"> <head>`

Attack `zj{{print "2932" "1257"}}zj`
Proof (from Location header): `Location: https://example.com/web/index.php/component/search/?searchword=ZAP&ordering=newest&searchphrase=all&areas[0]=zjprint29321257zj&Itemid=224`

The pattern is consistently that the attack parameter gets stripped of special characters and inserted into the page or URL. Since stripping the attack of special characters results in the concatenation of the two numbers, the test for concatenation doesn't differentiate between a correctly discovered evaluation of the attack parameter and an FP of the parameter getting cleaned and put back on the page without evaluation.

This definitely could be poor input parameter handling by the site, but I don't believe clears the threshold for SSTI.

I didn't dig into the history of the GoTemplateFormat to figure out why concatenation was used instead of multiplication like most of the others. Let me know if you want me to add the full software version info or help contribute in some way.

**Comment by kingthorin** [comment]
Thanks that's great. The details are highly appreciated ‼️ @rbliss

**Comment by kingthorin** [comment]
Fix is inbound, PR opened.

@tenaz3 & @rbliss thank you for providing great details. That really makes our lives easier as far as getting things fixed.

**Comment by rbliss** [comment]
Took a look at the PR, looks great. Thanks a ton for all you do @kingthorin
